### ISSUE TITLE
Don't import the whole tensorflow library

### ISSUE THREAD

**Issue by brandonskerritt** [Ciphey/Ciphey#116]
"It's f*cking huge"
One of the top complaints was installing a 500mb library just for tensorflow

**Comment by brandonskerritt** [comment]
It may be possible for us to use Tensorflow Lite, which is for android / IOS/ Raspberry Pi.
https://www.tensorflow.org/lite/examples
We **only** need load_model() in the production environment, will have to explore

**Comment by brandonskerritt** [comment]
https://www.tensorflow.org/lite/guide/inference
^^ How to load a model in tensorflow lite. 
@Cyclic3 they have a page for loading a tensorflow model in C++, do you think it would be better if we added this to Cipheycore and loaded it via that? The app is incredibly slow via PyPi and I want to reduce overhead as much as possible :)
https://www.tensorflow.org/lite/guide/inference#load_and_run_a_model_in_c

**Comment by brandonskerritt** [comment]
Tensorflow Lite Converter - Convert TF models into TF lite models
https://www.tensorflow.org/lite/convert/index

**Comment by Cyclic3** [comment]
Because I'm stubborn in my ways, I see this as yet another reason for #104. We could easily create a `cipheyai` module for installing the neural network component, allowing people to opt out of the large and intensive AI checking.

**Comment by Cyclic3** [comment]
cipheydists now uses the 'lite' models, with the h5 ones being moved to cipheyneuralnetwork. We can push that in a future release

**Comment by brandonskerritt** [comment]
For future reference, we switched to TF Lite as the install is 1mb compared to TF's 500mb.

**Comment by Cyclic3** [comment]
done
