### ISSUE TITLE
Ciphey could not find a matching cipheycore

### ISSUE THREAD

**Issue by brandonskerritt** [Ciphey/Ciphey#117]
https://i.imgur.com/6qyw0xV.png
@michalani

**Comment by brandonskerritt** [comment]
This is because cipheycore is in alpha / beta release and not a full release

**Comment by Cyclic3** [comment]
Ok, I think we have tested the prerelease enough. I'll convert it into a full release

**Comment by Cyclic3** [comment]
Done
