### ISSUE TITLE
4 seconds to detect no input

### ISSUE THREAD

**Issue by brandonskerritt** [Ciphey/Ciphey#118]
https://i.imgur.com/v8rI2HX.gifv
@michalani 
installed from pyPi

**Comment by brandonskerritt** [comment]
![image](https://user-images.githubusercontent.com/10378052/84332717-8fd01400-ab85-11ea-9af5-22deed9ba72d.png)

**Comment by brandonskerritt** [comment]
The very first thing Ciphey does is check for no input, why does it say ~4 seconds for Cipheys main() to first run? :(

**Comment by Cyclic3** [comment]
Can we have a trace output? I cannot repro, and this is running through cygwin, which is known to cause some performance problems!

**Comment by Cyclic3** [comment]
That also looks like some form of initialisation issue, probably fixed by #116

**Comment by Cyclic3** [comment]
On further talks with @michalani, we confirmed this is an instance of #116. 

Closing in favour of that issue.

**Comment by Cyclic3** [comment]
done in orwell
