### ISSUE TITLE
vigenere hangs on input "==="

### ISSUE THREAD

**Issue by brandonskerritt** [Ciphey/Ciphey#125]
**Describe the bug**
when the input into Ciphey is all equals signs, viginere hangs according to the debug output.

the minimum number of equals signs to reproduce this is 3.

**To Reproduce**
`ciphey -t "==="` on branch "fixing base"

**Comment by Cyclic3** [comment]
DW I fixed that

It now segfaults

**Comment by brandonskerritt** [comment]
@Cyclic3 fixed?

**Comment by Cyclic3** [comment]
Should be, yeah
