### ISSUE TITLE
Adding Distributions to AUR / WinGet / HomeBrew

### ISSUE THREAD

**Issue by bee-san** [Ciphey/Ciphey#137]
There wasn't an issue for this, so I decided to write one.

I am currently working on adding Ciphey to:
* WinGet
* AUR
* HomeBrew

I will write a blog post with how I did this, and link it here.

**Comment by brandonskerritt** [comment]
The Windows Manifest file is created, and we can create .msix files. I cannot test these, as the branch they are on is not working until _The Great ~~Orwellian~~ Refactor_ is completed.

**Comment by brandonskerritt** [comment]
For Windows release:

**Comment by brandonskerritt** [comment]
I am working on Arch

**Comment by SkeletalDemise** [comment]
Closing this because Ciphey is now packaged on both AUR and Homebrew. 🥳 As for WinGet I think it would be hard to package it because of CipheyCore.
