### ISSUE TITLE
Hope to add some new function

### ISSUE THREAD

**Issue by Martin-Winfred** [Ciphey/Ciphey#182]
This program is good at the regular type of encryption，but it can't Identify some of the uncommon encryption methods, such as URL and ROT. If that function can be added this program will be better.
And thank you for create a such wonderful program

**Comment by brandonskerritt** [comment]
Hey @Martin-Winfred ! Ciphey can identify rot, but not URL encoding. I'll add it to the **Big List of Things to do** :tm: 
https://github.com/Ciphey/Ciphey/issues/63 
:smile:
