### ISSUE TITLE
ImportError: cannot import name '_ciphey_core_py' from partially initialized module 'cipheycore'

### ISSUE THREAD

**Issue by Siegelcpp** [Ciphey/Ciphey#184]
I installed ciphey under macos 10.15.5 and encountered such an error. How to solve it? I installed it according to the steps in the document. 
![image](https://user-images.githubusercontent.com/44493013/88356466-7c29e700-cd9a-11ea-8e5b-c22eca8a76c9.png)

**Comment by brandonskerritt** [comment]
Hey!

Can you try installing Ciphey's release candidate?

`python3 -m pip instal lciphey==5.0.0rc9`

:D

**Comment by Cyclic3** [comment]
Just a note: I am having problems building cipheycore for macos python 3.7. If the problem persists with the rc, try running on python 3.8 (if possible).

I am in the process of overhauling the build system (again), as windows builds are completely failing

**Comment by Siegelcpp** [comment]
> 嘿!
> 
> 您可以尝试安装Ciphey的候选发行版吗？
> 
> `python3 -m pip instal lciphey==5.0.0rc9`
> 
> ：D

Thanks for your suggestion, I have tried it and it still doesn't work

> 嘿!
> 
> 您可以尝试安装Ciphey的候选发行版吗？
> 
> `python3 -m pip instal lciphey==5.0.0rc9`
> 
> ：D


Thank you for your suggestions, I have tried it and it still doesn’t work. Looking forward to your updates, this is a very promising tool

**Comment by Cyclic3** [comment]
I have fixed macos builds for python versions 3.7 and 3.8. Installing the latest ciphey (v5.0.0rc10) should give you something that works better

**Comment by Siegelcpp** [comment]
This is pretty cool, thanks for the update and I'll build it right away

**Comment by Cyclic3** [comment]
@Siegelcpp We've just pushed version 5 (`python3 -m pip install -U ciphey==5.0.0`), which definitely should not have this problem. Please feel free to reopen this issue if we have *really* screwed up and this still exists there!
