### ISSUE TITLE
File opening is failing

### ISSUE THREAD

**Issue by bee-san** [Ciphey/Ciphey#213]
**Describe the bug**
When the file contains hex encoded data:

```
    kwargs["text"] = kwargs["file_stdin"].read().decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 0: invalid start byte
```

**To Reproduce**
Use a hex encoded file
Try to import it into Ciphey

**Comment by sashreek1** [comment]
Hey! 
I would like to help fix this issue

**Comment by HexChaos** [comment]
> Hey!
> I would like to help fix this issue

Awesome Sashreek1! Please get to work fixing the issue and when your done do a pull request!

**Comment by sashreek1** [comment]
I am actually unable to recreate this issue,
I have used this file containing HEX encoded text and use 

`ciphey -f "hextest"`

and it works. This is what the file contained :
`68 65 6C 6C 6F 20 74 68 65 72 65`

and here is the output 

`(venv) [user@localhost tests]$ ciphey -f "hextest" ` 
`Result 'hello there' (y/N): y  `
`Format used:  `
`  hex  `
`Final result: "hello there"  `
