### ISSUE TITLE
Fix newline after final result

### ISSUE THREAD

**Issue by brandonskerritt** [Ciphey/Ciphey#214]
┌─[shardion@horizon]───[~/apks]───[04:34]
└─[$]─[0] ciphey - test_base64
Format used:
  utf8
  base64
Final result: "test base64 output
"

Appears to only be with Hex. Also you have a weird newline there, there's a little trick to print you can use to ignore the newline. print("test_str",end="")

**Comment by Cyclic3** [comment]
That's intended. If you run `echo AA | base64`, it gives you the base64 encoding of `414120`, as `echo` appends a newline.
