### ISSUE TITLE
Deciphering base64-encoded files yield no results when run with -i

### ISSUE THREAD

**Issue by TheAlcanian** [Ciphey/Ciphey#215]
**Describe the bug**
When running Ciphey on a base64-encoded file using the `-` command-line parameter, Ciphey picks up and decodes the base64-encoded file's contents, and prints the decoded content like normal. When running Ciphey on a base64-encoded file using the `-i` command-line parameter, Ciphey finds no results.

**To Reproduce**
1. What input did you use?
A sample file named `test_base64` with the contents `dGVzdCBiYXNlNjQgb3V0cHV0Cg==`
2. What flags / arguments did you use?
Command run was `ciphey -i test_base64`.

**Expected behavior**
Ciphey decodes the base64, outputs the decoded text and exits normally.

**Versions:**
 - OS/Distro: Gentoo Linux
 - Python version: Python 3.7.8
 - Ciphey versions: CipheyCore v0.2.4, CipheyDists v0.3.11, Ciphey v5.0.0rc10

**Comment by TheAlcanian** [comment]
Edited title because I remembered markdown doesn't work in titles

**Comment by brandonskerritt** [comment]
@all-contributors please add @TheAlcanian for bugs

**Comment by Cyclic3** [comment]
Can you run this with -vv (to give trace logging)?

**Comment by TheAlcanian** [comment]
[decoded_but_not_output.txt](https://github.com/Ciphey/Ciphey/files/5009992/decoded_but_not_output.txt)
Decoded, but not output?

**Comment by Cyclic3** [comment]
Ciphey seems to be loading the filename itself as the ciphertext, rather than as the input. The `-i` parameter actually doesn't really do anything atm, so I would omit it.

We are having difficulty reading in files with ciphey (hopefully fixed soon), so the best bet is to use `cat <file> | ciphey <flags...>` (or `type <file> | ciphey <flags...>` on windows`) until we get that fixed

**Comment by TheAlcanian** [comment]
Sounds good.

**Comment by SkeletalDemise** [comment]
I am closing this issue because it appears to be fixed. I can't reproduce the bug when doing `ciphey -f test_base64.txt` with `test_base64.txt` containing `dGVzdCBiYXNlNjQgb3V0cHV0Cg==`
