### ISSUE TITLE
Base64 encoded cipher: base64 encoded after encryption

### ISSUE THREAD

**Issue by aoprea1982** [Ciphey/Ciphey#232]
### Problem:
base64 encoded after encryption
The cipher is from owaspcrackme level1 [https://github.com/OWASP/owasp-mstg/tree/master/Crackmes](url)
Currently Ciphey does not decrypt or identify this payload.  Keeps Thinking!

```
 ciphey -i -t "5UJiFctbmgbDoLXmpL12mkno8HT4Lv8dlat8FxR2GOc=" --offline
🌏  Thinking
```

### Solution:
openssl to decode and decrypt the secret 

```
echo  5UJiFctbmgbDoLXmpL12mkno8HT4Lv8dlat8FxR2GOc= | openssl enc -aes-128-ecb -base64 -d -K 8d127684cbc37c17616d806cf50473cc
```

Thank you! 

Tsubasa

**Comment by Cyclic3** [comment]
@aoprea1982 With the information you have given us, it would seem like the only way to crack that (in the absence of more information) would be to brute-force a 128-bit key, which (for classical computers) would take more energy than there is in the solar system. The key `8d127684cbc37c17616d806cf50473cc` cannot be determined from the ciphertext in any much faster way (unless you have some groundbreaking new cryptanalytic method!)

For this reason, Ciphey does not support brute force AES keyspace attacks.

Please reopen this if I have misidentified the nature of your ciphertext, but I'm going to close this for the above reason.
