### ISSUE TITLE
Couldn't find cipheycore-0.2.9 on Windows

### ISSUE THREAD

**Issue by Soowin** [Ciphey/Ciphey#234]
**Describe the bug**
The latest version of cipheycore on Windows is 0.1.0, but ciphey requires 0.2.9 or higher 

**To Reproduce**
python version: 3.8 on Windows
pip version: 20.2
run 'pip install ciphey', it shows "Could not find a version that satisfies the requirement cipheycore<0.3.0,>=0.2.8 (from ciphey) (from versions: 0.0.1, 0.1.0)"
![4(SG`$1V_01UMO5L(OWZ_9O](https://user-images.githubusercontent.com/33149289/89288004-83e56780-d687-11ea-8e4a-d3fa669ffc28.png)

But on Linux, it will install cipheycore-0.2.9-cp38-cp38-manylinux2014_x86_64.whl, which is the latest version of cipheycore.
![批注 2020-08-04 192047](https://user-images.githubusercontent.com/33149289/89288076-a11a3600-d687-11ea-8027-1841983bf941.png)

On the [page of cipheycore](https://github.com/Ciphey/CipheyCore) it shows Windows release build failing

**Comment by brandonskerritt** [comment]
@Cyclic3 ☹️ sad bois incorporated

**Comment by brandonskerritt** [comment]
can you run the command exactly as shown on the GitHub README? it might solve your problems. can you.also confirm whether or not your windows install is Python 3? :)

**Comment by NigelWidner** [comment]
I am having the same issue on Windows in the terminal trying to install Ciphey, I get a Ciphey Core issue. I am running Python 3.8.2.

Running: 
"python -m pip install -U ciphey"
ERROR: Could not find a version that satisfies the requirement cipheycore<0.3.0,>=0.2.8 (from ciphey) (from versions: 0.0.1, 0.1.0)
ERROR: No matching distribution found for cipheycore<0.3.0,>=0.2.8 (from ciphey)

Running: 
"python**3** -m pip install -U ciphey" does nothing for some reason, no output on the command line.

I tried to install cipheycore manually: 
"python -m pip install -U cipheycore==0.2.9"
ERROR: Could not find a version that satisfies the requirement cipheycore==0.2.9 (from versions: 0.0.1, 0.1.0)
ERROR: No matching distribution found for cipheycore==0.2.9

I did verify my pip is updated:
"python -m pip install --upgrade pip"
Requirement already up-to-date: pip in c:\users\xxxxxxx\appdata\local\programs\python\python38-32\lib\site-packages (20.2.1)

**Comment by Cyclic3** [comment]
@NigelWidner Would it be possible for you to update to the latest pytthon 3.8 (3.8.5) and try again?

**Comment by Cyclic3** [comment]
Are you running on a 32 bit machine?

**Comment by joaovarelas** [comment]
**Solved** by running `$ python3 -m pip install --upgrade pip`

**Comment by Cyclic3** [comment]
Great! Glad you got it working :)

**Comment by NigelWidner** [comment]
I just wanted to add, I solved this by having to install Python through the Windows App Store instead of the standalone package.
