### ISSUE TITLE
https://docs.ciphey.online/ call

### ISSUE THREAD

**Issue by Apocsword** [Ciphey/Ciphey#252]
Want to be able to install this into my phone

**Comment by Cyclic3** [comment]
@Apocsword Do you mean installing ciphey on your phone?

We are working on a webapp, which would work on mobile devices

**Comment by Apocsword** [comment]
That be bad ass!!

**Comment by Cyclic3** [comment]
I'll close this, as this is already in the works. Please reopen if there is anything more!
