### ISSUE TITLE
fish: 'ciphey' terminated by signal SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by Audition-CSBlock** [Ciphey/Ciphey#253]
SIGSEGV error

**Reproduce:**
install ciphey using the guide on macos using python3.8.5

**Expected behavior:**
that it works

**Versions:**
 - OS X Catalina
 - Python 3.8.5
 - Ciphey versions: ciphey5.1.0 cipheycore0.2.9 cipheydists0.3.18

**Comment by Cyclic3** [comment]
Can you please give an example ciphertext that triggers this?

**Comment by Audition-CSBlock** [comment]
> Can you please give an example ciphertext that triggers this?

Well it happens when i run ciphey itself, so even if i give any input it will still give me a SIGSEGV

**Comment by Cyclic3** [comment]
Is this the same as #256?

**Comment by Audition-CSBlock** [comment]
@Cyclic3 looked through it and it doesn't seem like it, sorry for the late response, had some stuff to do.

**Comment by Cyclic3** [comment]
Could you try cloning and running the `xor-ciphers` branch? It should hopefully fix this problem

**Comment by Audition-CSBlock** [comment]
@Cyclic3 i cloned it but i've tried running it and there is no documentation for that, i've looked around in directories but can't get it to work. any help on running it from scratch?

**Comment by Audition-CSBlock** [comment]
when i try and run it on py3.7.7 it gives me this error (might be of any help?) i also hid the user dir names:
`Traceback (most recent call last):
  File "/Users//.pyenv/versions/3.7.7/bin/ciphey", line 5, in <module>
    from ciphey.ciphey import main
  File "/Users//.pyenv/versions/3.7.7/lib/python3.7/site-packages/ciphey/__init__.py", line 1, in <module>
    from . import common
  File "/Users//.pyenv/versions/3.7.7/lib/python3.7/site-packages/ciphey/common.py", line 4, in <module>
    import cipheycore
  File "/Users//.pyenv/versions/3.7.7/lib/python3.7/site-packages/cipheycore/__init__.py", line 13, in <module>
    from . import _ciphey_core_py
ImportError: dlopen(/Users//.pyenv/versions/3.7.7/lib/python3.7/site-packages/cipheycore/_ciphey_core_py.so, 2): Library not loaded: /usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/Python
  Referenced from: /Users//.pyenv/versions/3.7.7/lib/python3.7/site-packages/cipheycore/_ciphey_core_py.so
  Reason: image not found`

**Comment by Cyclic3** [comment]
Did you upgrade cipheycore to 0.3.0-rc4?

**Comment by Audition-CSBlock** [comment]
@Cyclic3 yes, i upgraded both, on both py3.8.5 and py3.7.7, both still fail:

3.8.5:
`'ciphey' terminated by signal SIGSEGV (Address boundary error)`

3.7.7:
`Traceback (most recent call last):
  File "/Users//.pyenv/versions/3.7.7/bin/ciphey", line 5, in <module>
    from ciphey.ciphey import main
  File "/Users//.pyenv/versions/3.7.7/lib/python3.7/site-packages/ciphey/__init__.py", line 1, in <module>
    from . import common
  File "/Users//.pyenv/versions/3.7.7/lib/python3.7/site-packages/ciphey/common.py", line 4, in <module>
    import cipheycore
  File "/Users//.pyenv/versions/3.7.7/lib/python3.7/site-packages/cipheycore/__init__.py", line 13, in <module>
    from . import _ciphey_core_py
ImportError: dlopen(/Users//.pyenv/versions/3.7.7/lib/python3.7/site-packages/cipheycore/_ciphey_core_py.so, 2): Library not loaded: /usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/Python
  Referenced from: /Users//.pyenv/versions/3.7.7/lib/python3.7/site-packages/cipheycore/_ciphey_core_py.so
  Reason: image not found`

**Comment by Audition-CSBlock** [comment]
@Cyclic3 hey! i think i found the issue, i tried running and installing ciphey on my default python installation (no pyenv) and it worked! so it must have something to do with pyenv, I'll look into it more.

this also may be the solution for #256

**Comment by Cyclic3** [comment]
@Audition-CSBlock That's great news! If you can track down exactly why the MacOS pyenv causes all these problems, please do let us know!

I have to admit that my knowledge of MacOS is rather limited, so any help you could provide would be much appreciated.

**Comment by Audition-CSBlock** [comment]
@Cyclic3 I am still searching left and right but it seems to be a big problem to this day.

I am also new to Mac, got tired of Microsoft's bullshit and switched to Linux for my desktop and Mac for my new laptop. Mac works kinda like linux and their laptops are sleek which I prefer more than powerhungry bulky laptops :).

**Comment by Audition-CSBlock** [comment]
@Cyclic3 also, mind if I leave this issue open? There might be other people with more useful info.

**Comment by chrisdukey** [comment]
Just had this same issue on Catalina. Turns out ciphey was looking for the Frameworks directory in `/usr/local/opt/python@3.7` whereas my python 3 directory was just `/usr/local/opt/python3`. I created a symbolic link in `/url/local/opt` and that fixed it (`ln -s python3 python@3.7`).

**Comment by Audition-CSBlock** [comment]
@chrisdukey haha! exactly what i did 2 days ago, forgot to add the comment. Thanks for confirming! 👍

**Comment by bee-san** [comment]
> Just had this same issue on Catalina. Turns out ciphey was looking for the Frameworks directory in `/usr/local/opt/python@3.7` whereas my python 3 directory was just `/usr/local/opt/python3`. I created a symbolic link in `/url/local/opt` and that fixed it (`ln -s python3 python@3.7`).

I don't think there's anyway for us to incorporate this into Ciphey itself :( I'll leave a note on the installation page though. Thanks so much for contributing :D

**Comment by Audition-CSBlock** [comment]
@bee-san I actually think there may be a way! I've looked through the cipheycore repo and saw some lines including the path of python.

Sadly though I don't know much about c++ but @Cyclic3 might since he wrote much of the code I think? Hope this helps a bit :).

**Comment by bee-san** [comment]
This is being fixed in #591

**Comment by Audition-CSBlock** [comment]
@bee-san ty!
