### ISSUE TITLE
Termux installation failed

### ISSUE THREAD

**Issue by zainarbani** [Ciphey/Ciphey#264]
**Describe the bug**
The latest version of cipheycore on Termux is 0.1.0, but ciphey requires 0.2.9 or higher.

**To Reproduce**
1. pip install ciphey --upgrade
2. pip install cipheycore==0.2.9

**Versions:**
 - OS/Distro: Linux arm64, Android 10 (Termux)
 - Python version: 3.8.2

![Screenshot_20200808-032507](https://user-images.githubusercontent.com/31644731/89686278-481cfd00-d928-11ea-94ad-15f4dd4ba94b.jpg)

**Comment by Cyclic3** [comment]
We do not currently have an android build of cipheycore (the C++ library that does the more intensive tasks). 

However, you can build your own one using the documentation here (freshly created for this issue).

**Comment by zainarbani** [comment]
> We do not currently have an android build of cipheycore (the C++ library that does the more intensive tasks).
> 
> However, you can build your own one using the documentation here (freshly created for this issue).

Thanks for your response, 
I will try it.
