### ISSUE TITLE
macOS, pip install, Could not find cipheycore==0.2.9

### ISSUE THREAD

**Issue by reber0** [Ciphey/Ciphey#266]
macOS Mojave 10.14.6

[10:12 xxx@xxx at ~/Downloads/Ciphey git:(master) ✗]
➜  python3 --version
Python 3.8.5
[10:15 xxx@xxx at ~/Downloads/Ciphey git:(master) ✗]
➜  python3 -m pip install --upgrade pip
Requirement already up-to-date: pip in /usr/local/lib/python3.8/site-packages (20.2.1)

[10:12 xxx@xxx at ~/Downloads/Ciphey git:(master) ✗]
➜  pip3 install -r requirements.txt
Ignoring atomicwrites: markers 'sys_platform == "win32"' don't match your environment
Ignoring importlib-metadata: markers 'python_version < "3.8"' don't match your environment
Ignoring mypy-extensions: markers 'python_version >= "3.7" and python_version < "3.8"' don't match your environment
Ignoring typing-inspect: markers 'python_version >= "3.7" and python_version < "3.8"' don't match your environment
Ignoring win32-setctime: markers 'sys_platform == "win32"' don't match your environment
Ignoring zipp: markers 'python_version < "3.8"' don't match your environment
Requirement already satisfied: alabaster==0.7.12 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (0.7.12)
Requirement already satisfied: appdirs==1.4.4 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (1.4.4)
Requirement already satisfied: astroid==2.4.2 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (2.4.2)
Requirement already satisfied: attrs==19.3.0 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 13)) (19.3.0)
Requirement already satisfied: babel==2.8.0 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 16)) (2.8.0)
Requirement already satisfied: base58==2.0.1 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 19)) (2.0.1)
Requirement already satisfied: black==19.10b0 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 22)) (19.10b0)
Requirement already satisfied: certifi==2020.6.20 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 25)) (2020.6.20)
Requirement already satisfied: chardet==3.0.4 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 28)) (3.0.4)
ERROR: Could not find a version that satisfies the requirement cipheycore==0.2.9 (from -r requirements.txt (line 31)) (from versions: 0.0.1, 0.1.0)
ERROR: No matching distribution found for cipheycore==0.2.9 (from -r requirements.txt (line 31))
[10:17 xxx@xxx at ~/Downloads/Ciphey git:(master) ✗]
➜  python3 -m pip install ciphey --upgrade
Collecting ciphey
  Using cached ciphey-5.1.0-py3-none-any.whl (51 kB)
ERROR: Could not find a version that satisfies the requirement cipheycore<0.3.0,>=0.2.8 (from ciphey) (from versions: 0.0.1, 0.1.0)
ERROR: No matching distribution found for cipheycore<0.3.0,>=0.2.8 (from ciphey)

**Comment by dlimanov** [comment]
Yep, having the same issue on 10.14.6

**Comment by deepio** [comment]
well... until they get around to it... `pip install ciphey==3.5.7` works

**Comment by dlimanov** [comment]
> well... until they get around to it... `pip install ciphey==3.8.2` works

thanks @deepio, that indeed worked!

**Comment by deepio** [comment]
@reber0 until the authors fix this, I think this is still an issue and should remain open. What do you think?

**Comment by brandonskerritt** [comment]
> well... until they get around to it... `pip install ciphey==3.8.2` works

I **HIGHLY** suggest not using that version :cry:

**Comment by deepio** [comment]
@brandonskerritt I'm very well aware, but despite your best efforts (which I'm really happy to see, honestly! you have a stance of not pushing a new version unless all tests pass and it's fantastic! ) we still can't use the latest versions without building cipheycore locally.

**Comment by brandonskerritt** [comment]
Hey!!

Someone made a docker image, can you try and use this? It uses the latest version (which has a slight bug in the output, [old green] is printed because of some weird char escaping, but its fixed in #275 )

```
docker run -it cmnatic/ciphey:debian-buster
```

**Comment by deepio** [comment]
I'm looking forward to using the docker version until this issue is resolved, thank you.

**Comment by deepio** [comment]
I looked into it further. @brandonskerritt The problem has nothing to do with your code. 

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on github only runs the latest catalina for actions. I tend to use travis because there are more options here, but they have problems too.  

https://github.com/Ciphey/CipheyCore/blob/master/.github/workflows/build-macos.yaml#L9 
`cipheycore` only builds on catalina, any other macOS will not work. I stayed because I must use 32-bit for the time being, catalina is 64-bit only.

**Comment by Cyclic3** [comment]
@deepio You can build cipheycore yourself if you wish to have a version that works natively. The instructions at https://github.com/Ciphey/CipheyCore/blob/master/README.md are pretty comprehensive

**Comment by deepio** [comment]
> ... without building cipheycore locally.

Yes, much appreciated 👍

**Comment by tuminoid** [comment]
Currently, pip3/Python 3.6.9 says ciphey 5.3.2 is requiring cipheycore >=0.15 <0.2.0, but available package is 0.2.9, so at the moment ciphey cannot be installed.

**Comment by brandonskerritt** [comment]
> Currently, pip3/Python 3.6.9 says ciphey 5.3.2 is requiring cipheycore >=0.15 <0.2.0, but available package is 0.2.9, so at the moment ciphey cannot be installed.

Ciphey does not support python 3.6.9, only Python 3.7 and higher :)

**Comment by tuminoid** [comment]
> > Currently, pip3/Python 3.6.9 says ciphey 5.3.2 is requiring cipheycore >=0.15 <0.2.0, but available package is 0.2.9, so at the moment ciphey cannot be installed.
> 
> Ciphey does not support python 3.6.9, only Python 3.7 and higher :)

https://docs.ciphey.online/en/latest/install.html says 3.6 🙁

**Comment by brandonskerritt** [comment]
> > > Currently, pip3/Python 3.6.9 says ciphey 5.3.2 is requiring cipheycore >=0.15 <0.2.0, but available package is 0.2.9, so at the moment ciphey cannot be installed.
> > 
> > 
> > Ciphey does not support python 3.6.9, only Python 3.7 and higher :)
> 
> https://docs.ciphey.online/en/latest/install.html says 3.6 slightly_frowning_face

Oh no!!! We're moving away from that docs page to a GitHub wiki :-( Where did you find the link for that? is it buried in the README? 

So sorry! We're still in the process of moving :sweat_smile:

**Comment by tuminoid** [comment]
> > > > Currently, pip3/Python 3.6.9 says ciphey 5.3.2 is requiring cipheycore >=0.15 <0.2.0, but available package is 0.2.9, so at the moment ciphey cannot be installed.
> > > 
> > > 
> > > Ciphey does not support python 3.6.9, only Python 3.7 and higher :)
> > 
> > 
> > https://docs.ciphey.online/en/latest/install.html says 3.6 slightly_frowning_face
> 
> Oh no!!! We're moving away from that docs page to a GitHub wiki :-( Where did you find the link for that? is it buried in the README?
> 
> So sorry! We're still in the process of moving 😅

It's like first link top of the readme.md: "Installation Guide" 🤭 Thanks for letting me know.

**Comment by SkeletalDemise** [comment]
Closing this because currently Ciphey can be installed on MacOS via Homebrew, Docker, or MacPorts. There are many options now. 🥳
