### ISSUE TITLE
Incorrect format loading

### ISSUE THREAD

**Issue by brignano** [Ciphey/Ciphey#271]
Shouldn't line 227 below be `config.update_format("out", "bytes")`?

https://github.com/Ciphey/Ciphey/blob/a26abe0da2794efea00694fc32cd1554374f4e71/ciphey/ciphey.py#L222-L227

https://github.com/Ciphey/Ciphey/blob/a26abe0da2794efea00694fc32cd1554374f4e71/ciphey/iface/_config.py#L67

**Comment by Cyclic3** [comment]
Yes, you are absolutely right!

@all-contributors please add @brignano for bug

**Comment by Cyclic3** [comment]
*sigh*

**Comment by brignano** [comment]
Closed by #270
