### ISSUE TITLE
Error during pip install re: tensorflow on Ubuntu

### ISSUE THREAD

**Issue by packetrat** [Ciphey/Ciphey#274]
Could not find a version that satisfies the requirement tensorflow<3.0.0,>=2.1.0 (from ciphey) (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.10.1, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.2, 1.12.3, 1.13.0rc0, 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
No matching distribution found for tensorflow<3.0.0,>=2.1.0 (from ciphey)

**Comment by brandonskerritt** [comment]
Ciphey does not use tensorflow :) Please fill out the full bug template, and make sure you are installing the latest version of Ciphey with Python 3+ :)

**Comment by Cyclic3** [comment]
After hacking away at this on a docker container for an hour, I found the solution:

```bash
sudo apt-get install python3.8 # The minimum required by ciphey is 3.7, but why stop there?
python3.8 -m pip install -U ciphey # Or ciphey==5.2.0 if that doesn't work
```

Please reopen if this doesn't work for you!
