### ISSUE TITLE
X&Y does not work with spaces

### ISSUE THREAD

**Issue by brandonskerritt** [Ciphey/Ciphey#276]
X&Y decryptor does not work with spaces.

# From code review

This is making the assumption that the string only contains 2 chars, which is wrong I believe. Binary strings in CTFs often have spaces, commas, new lines to delimiter themselves:
https://gchq.github.io/CyberChef/#recipe=To_Binary('Space')&input=aGVsbG8gbXkgbmFtZSBpcw

Honestly the way I would do it would be the way you're doing it but adding in another one.

Imo, if it's hard to do this then the function isn't right -- it should theoretically be possible to construct a single function which operates on X and Y, X and Y and P, and so on ad infinitum

Is there anyway you can make a single function? Abstract away the code? :)

If you had to make a function to do this, but you got told you didn't know how many chars were in the input, how would you abstract away hardcoded values into a one-size-fits-all solution? :)

Even if you gave rough psuedocode, I can help you fill it in :)

_Originally posted by @brandonskerritt in https://github.com/Ciphey/Ciphey/pull/258/files_

**Comment by lukasgabriel** [comment]
Currently, it _will_ work with spaces, but not with any other delimiter.

*Example:* 
```
poetry run ciphey -t "    7  y7y7 y77 7yy77y7y 7yyy7    7yy 7yyy7y77 77y7 77 77 7y 77y y y   y7yy7yyy7 7yy77y7y 77y77777 7y7y7y77 7yyy7yyy 7yy7yyyy 77y777777y7y7y77 7yy7y777 7yyy77y7   7yy 77y7y 7yy77 y7y "
```

*Output:*
```
Format used:
  atbash
  xandy:
    Key: 7 -> 0 & b -> 1
Final result: "Test One Two Three"

```
