### ISSUE TITLE
Switch out the current `answer_str` used in tests for a pangram.

### ISSUE THREAD

**Issue by lukasgabriel** [Ciphey/Ciphey#280]
Unrelated idea: Switch out the current `answer_str` for a pangram such as `The quick brown fox jumps over the lazy dog` or `Sphinx of black quartz, judge my vow`. This would help detect errors in output that only affect certain characters - which, for example, my galactic decoder is struggling with.

_Originally posted by @lukasgabriel in https://github.com/Ciphey/Ciphey/pull/265/review_comment/create_

**Comment by brandonskerritt** [comment]
actually believe it or not but we have a program which auto generated mass amounts of tests using random strings from.books etc, it's called generate_tests.py and is in tests/ directory 😂😂 we haven't used it in over a month though, but it's very good to generate 200k tests or so :)

**Comment by brandonskerritt** [comment]
Also Cyclic3 begged me to stop using it as our CI would time out if I accidentally uploaded the tests
