### ISSUE TITLE
Input causes infinite loop; Percent signs in input cause issues

### ISSUE THREAD

**Issue by lukasgabriel** [Ciphey/Ciphey#282]
**INPUT:**
```
%0  0 0 %        0 % %%0    0%% 0%  0   %000 %   %0 0 % 000  % 0   %% %%0 %  %%   % %%  00  %000 0   %0 0 % 000 %%0    0% %0 %0   %  %0%%%%     %  % 0 00  % 0 % % %0   00% 0  0     0      %0 0%000 0% %0 %%%%%    % 00 0 %0  %%%0 0  %    0 %     %%%  0 00 % %  0%   % 0  0%% 0  %  0 %00 %%   0  %0
```

Program will output the following indefinitely:
` TRACE    | ciphey.basemods.Checkers.brandon:checker:154 - To analyse is [] `

 - Windows 10 1909
 - Python 3.7
 - Ciphey 5.2.0

X-Y cracker will sometimes fail due to unknown reasons when a `%` is part of the cstring, mostly when combined with other symbols such as an underscore, a period or an asterisk. Sometimes this will happen immediately, other times it will result in the aforementioned infinite loop. I will update this issue with more cases.

**Comment by bee-san** [comment]
Pretty sure this is caused by the while loop in `autumn` checker :(

**Comment by lukasgabriel** [comment]
@all-contributors please add @lukasgabriel for bug reports

**Comment by lukasgabriel** [comment]
Two bugs for the price of one

**Comment by lukasgabriel** [comment]
@all-contributors please add @lukasgabriel for bug

**Comment by lukasgabriel** [comment]
@all-contributors please add @lukasgabriel for bug

**Comment by bee-san** [comment]
This is fixed :)
