### ISSUE TITLE
Installing ciphey failed in Windows 7

### ISSUE THREAD

**Issue by AaronBitman** [Ciphey/Ciphey#287]
I tried to install ciphey with pip. I got:

  Could not find a version that satisfies the requirement cipheycore(0.3.0,)=0.2.8 (from ciphey) (from versions: )
No matching distribution found for cipheycore(0.3.0,)=0.2.8 (from ciphey)

**Versions:**
- Windows 7 Professional version 6.1 (Build 7601: Service Pack 1)
- Python version: 3.7.4
- pip version: First 19.0.3, and when that failed, 20.2.2

**Comment by brandonskerritt** [comment]
Please read our wiki page on installation on Windows :)
