### ISSUE TITLE
ciphey always stuck up

### ISSUE THREAD

**Issue by phspade** [Ciphey/Ciphey#300]
Hi,

Every time I run `ciphey -t "<some encoding>"` it's always stuck in "Thinking".

**Comment by lukasgabriel** [comment]
Hello @phspade ,
please provide us with the following information so we can diagnose the issue:

1. What inputs did you use?
2. Which flags / arguments did you use?
3. On which OS & version are you running ciphey? 

If you have time, please run Ciphey with `ciphey -vvv` and post the results (either as a file, or copied & pasted) here.

Thanks a lot  😄

**Comment by phspade** [comment]
Hi @lukasgabriel,

>What inputs did you use?
Which flags / arguments did you use?

I just used the `-t` option. Now I run the same command `ciphey -t <mu encoding> -vvv` and I discover that it's still running and it looks like it's taking too long.

>On which OS & version are you running ciphey?

Running it on my VPS which is Latest Parrot OS.

Just a quick reminder. Maybe instead of the world icon logo/gif. Try to change it by some progress bar or percentage so that user will know that it's running an not that really stuck 👍

**Comment by lukasgabriel** [comment]
Thank you for providing more info!

Could you maybe share the inputs that you used as well? Do you know what they are encoded/encrypted with?
If you could provide any logs that would be great as well.

If Ciphey is running for a very long time, it's most likely that it has entered an infinite loop and is not going to find a solution.
So the best way to troubleshoot this would be to look at the logs and figure out what is causing that loop. Otherwise we really don't have any way of knowing what's going on on your end 😄 

Thanks again

**Comment by Cyclic3** [comment]
As a side note, a progress bar *is* something we looked at, but our ability to handle nested ciphers makes it impossible to determine a useful "progress" heuristic. That being said, we are looking at redoing it to use some entropy heuristic at some point.

**Comment by lukasgabriel** [comment]
I'm sorry, but without any kind of logs or info about the input you used, we cannot provide support. Feel free to open a new issue & diligently fill out the Issue Template - then we'll come back to it and hopefully be able to provide a solution :)

**Comment by tushroy** [comment]
experiencing same with following input
`ciphey -t "KFMGQ3C2K5TWOVKHNBZFUWDDOVEUORTPMNBUEMDBGNTWOY3NNB2Q===="`

its just stuck

**Comment by nicolaipre** [comment]
@lukasgabriel Since nobody posted any debug logs here, here is one for reference for a similar problem.

Seems like it always gets stuck at xorcrypt. 

```
2020-12-24 17:38:16.448 | DEBUG    | ciphey.basemods.Crackers.xorcrypt:attemptCrack:83 - Trying xorcrypt cipher on b'bVB1tKMl0EauVnISRak5saZ5TA=='
2020-12-24 17:38:16.448 | TRACE    | ciphey.basemods.Crackers.xorcrypt:attemptCrack:102 - Got possible length 1
2020-12-24 17:38:16.450 | DEBUG    | ciphey.basemods.Searchers.ausearch:search:263 - At depth 2
2020-12-24 17:38:16.451 | TRACE    | ciphey.basemods.Searchers.ausearch:search:269 - 8864 remaining on this level
...

```
