### ISSUE TITLE
Base62 decoding is not working

### ISSUE THREAD

**Issue by SkeletalDemise** [Ciphey/Ciphey#310]
**Describe the bug**
Base62 decoding is not working properly.

**To Reproduce**
1. What input did you use?
`ciphey -t "126hVJJr0BxMumjWTECjbf0W5wF4DFPXG1NcA"`
2. What flags / arguments did you use?
N/A

**Verbose Output**
N/A because it silently fails and there's no logging for Base62.

**Expected behavior**
That Ciphey can decode Base62 properly.

**Versions:**
 - OS/Distro: `Windows 10`
 - Python version: `Python 3.7.7`
 - Ciphey versions: `Ciphey 5.3.1, cipheycore 0.2.9, cipheydists 0.3.20`

**Additional context**
It seems the package that Ciphey uses to decode Base62 doesn't work.

**Comment by brandonskerritt** [comment]
Fixed in #311
