### ISSUE TITLE
Cracking huge ciphertext causes OOM

### ISSUE THREAD

**Issue by bee-san** [Ciphey/Ciphey#319]
"Ciphey succeeds in decoding it as base64, but then gets stuck trying to crack such a huge ciphertext (probably on vigenere). Whilst hanging is rather expected, it should definitely not cause an OOM condition on your system! I'll see if I can track down the memory-hogging function, and fix this." from @Cyclic3 in #269

**Comment by Cyclic3** [comment]
Wow someone should really do something about that /s

I'm currently doing a whole bunch of stuff to the core to get the xorcrypt stuff reliable, so I'll come back to this when that codebase is more stable

**Comment by Cyclic3** [comment]
Can't repro in the latest master after the latest cipheycore refactoring, so i think this is done

**Comment by Cyclic3** [comment]
ermmmmm, it's allocing more and more now

**Comment by bee-san** [comment]
This is being fixed in #591 (presumably)
