### ISSUE TITLE
Add support for Nullcipher-like inputs (i.e. NATO Alphabet)

### ISSUE THREAD

**Issue by lukasgabriel** [Ciphey/Ciphey#336]
Add support for plaintext that is hidden in a bunch of other plaintext - for example, the first letter of every word in a sentence forming the solution.

A _subset_ of this problem would be adding support for words written in the NATO phonetic alphabet.

**Comment by lukasgabriel** [comment]
I'm currently working on this. 
A major obstacle is the fact that the language checker will see the english words in the plaintext and cause ciphey to stop before finding the acutal solution.

**Comment by bee-san** [comment]
#338 relates to this problem

**Comment by bee-san** [comment]
This is fixed by the human checker.
