### ISSUE TITLE
Add support for Prisoner's Tap Code

### ISSUE THREAD

**Issue by lukasgabriel** [Ciphey/Ciphey#337]
Hello spoooopyyy hackers :jack_o_lantern: 

This is a Hacktoberfest only issue! :ghost: 

Find our contributing guidelines here, this walks you through how to add a decoder / cracker! 
https://github.com/Ciphey/Ciphey/wiki#adding-your-own-crackers--decoders

Don't worry if it looks hard, we will walk you through everything! :) 

**Write this issue in Python!**

# Links
These links will help you understand how this works!

https://en.wikipedia.org/wiki/Tap_code

**Comment by MikeMerz** [comment]
Hey, is the issue still open? , if so , the tapping will be represented by a tuple of 2 ints?

**Comment by bee-san** [comment]
@SkeletalDemise Is adopting this, I think

**Comment by bee-san** [comment]
@Itamikame this is the issue :)
