### ISSUE TITLE
Add ROT47 cracker

### ISSUE THREAD

**Issue by lukasgabriel** [Ciphey/Ciphey#342]
Hello spoooopyyy hackers :jack_o_lantern: 

This is a Hacktoberfest only issue! :ghost: 

Find our contributing guidelines here, this walks you through how to add a decoder / cracker! 
https://github.com/Ciphey/Ciphey/wiki#adding-your-own-crackers--decoders

Don't worry if it looks hard, we will walk you through everything! :) 

**Write this issue in C++!**

# Links
These links will help you understand how this works!

https://www.dcode.fr/rot-47-cipher
https://en.wikipedia.org/wiki/ROT13#Variants
https://www.browserling.com/tools/rot47

**Comment by aldogutierrez** [comment]
Hello! I would like to contribute to this issue

**Comment by bee-san** [comment]
> Hello! I would like to contribute to this issue
Hey! Sure :D We're in the Discord discussing the best way for you to do this right now :) :sparkles:

**Comment by SkeletalDemise** [comment]
Hello, just to let everyone know, this will have to be written in C++ as a cracker. ROT47 uses an alphabet of ASCII characters 33 to 126, making an alphabet length of 94. Only adding ROT47 would be like only adding ROT13 without adding ROT 1-25.

We'll need a cracker that can decode ROT 1-94 using the ROT47 alphabet. It should be easy to just use the existing caesar cracker with the ROT47 alphabet.
