### ISSUE TITLE
Add ASCII shift cracker

### ISSUE THREAD

**Issue by lukasgabriel** [Ciphey/Ciphey#343]
Hello spoooopyyy hackers :jack_o_lantern: 

This is a Hacktoberfest only issue! :ghost: 

Find our contributing guidelines here, this walks you through how to add a decoder / cracker! 
https://github.com/Ciphey/Ciphey/wiki#adding-your-own-crackers--decoders

Don't worry if it looks hard, we will walk you through everything! :) 

**Write this issue in C++!**

# Links
These links will help you understand how this works!

https://www.dcode.fr/ascii-shift-cipher

**Comment by jacobggman** [comment]
Can I do this in Python? Because there are only 128 possibilities (if I don't wrong)

**Comment by SkeletalDemise** [comment]
This will need to be written in C++ as a cracker, just like ROT47. It will need to decode ROT 1-128 using the full ASCII alphabet. It should be easy to just use the existing caesar cracker with the full ASCII alphabet.
