### ISSUE TITLE
Add A1Z26 decoder

### ISSUE THREAD

**Issue by lukasgabriel** [Ciphey/Ciphey#344]
This one's mega-easy, so have a go :)
https://planetcalc.com/4884/

**Comment by SkeletalDemise** [comment]
Hi, in case anyone is thinking of working on this, A1Z26 is already completed by me. There are issues however that can only be solved with the entropy checker. A1Z26 will be implemented into Ciphey once the entropy checker is done and implemented. See here: https://github.com/Ciphey/Ciphey/wiki/Checkers,-explained#entropy-coming-soon
