### ISSUE TITLE
Add affine cracker

### ISSUE THREAD

**Issue by lukasgabriel** [Ciphey/Ciphey#346]
Hello spoooopyyy hackers :jack_o_lantern: 

This is a Hacktoberfest only issue! :ghost: 

Find our contributing guidelines here, this walks you through how to add a decoder / cracker! 
https://github.com/Ciphey/Ciphey/wiki#adding-your-own-crackers--decoders

Don't worry if it looks hard, we will walk you through everything! :) 

**Write this issue in Python!**

# Links
These links will help you understand how this works!

https://en.wikipedia.org/wiki/Affine_cipher
https://www.geeksforgeeks.org/implementation-affine-cipher/

**Comment by Ozzyz** [comment]
I'll take a stab at this :)  Should the cracker be written in Python? There are only C=|A|*B possible combinations where |A| are all the A values that are coprime with alfabet length. Depending on alfabet length, this is very few combinations - 312 in the case of an alfabet length of 26. So I guess this is fairly inexpensive to perform in Python.

**Comment by bee-san** [comment]
> I'll take a stab at this :) Should the cracker be written in Python? There are only C=|A|*B possible combinations where |A| are all the A values that are coprime with alfabet length. Depending on alfabet length, this is very few combinations - 312 in the case of an alfabet length of 26. So I guess this is fairly inexpensive to perform in Python.

Ah, 312 sounds very cheap so go ahead :D
