### ISSUE TITLE
Add Brainfuck interpreter

### ISSUE THREAD

**Issue by lukasgabriel** [Ciphey/Ciphey#353]
https://www.dcode.fr/brainfuck-language
https://en.wikipedia.org/wiki/Brainfuck

**Comment by Cyclic3** [comment]
Maybe instead of a brainfuck deobfusicator (which is a ton of effort!), we use a time-limited emulator when we believe something to be brainfuck, replacing the "write to output" command `.` with something that appends to a string. Input would be a little more tricky, however.

**Comment by mav8557** [comment]
Hi!

I think I could take this one. To handle character input I might need some guidance on how and if that's something that's needed.

**Comment by maniac-en** [comment]
Brainfuck isn't working for me, I was doing a task from tryhackme [room](https://tryhackme.com/room/ctfcollectionvol1)

#### Encoded text

```
++++++++++[>+>+++>+++++++>++++++++++<<<<-]>>>++++++++++++++.------------.+++++.>+++++++++++++++++++++++.<<++++++++++++++++++.>>-------------------.---------.++++++++++++++.++++++++++++.<++++++++++++++++++.+++++++++.<+++.+.>----.>++++.
```
#### Expected output
```
THM{0h_my_h34d}
```
#### Actual output
![Screenshot from 2020-10-05 00-38-12](https://user-images.githubusercontent.com/45049766/95024809-1d8abe80-06a3-11eb-9496-813ec9e283cd.png)

**Comment by SkeletalDemise** [comment]
Brainfuck was added very recently. Ciphey release 5.8.0 is not on PyPI yet, so you cannot pip install it. You'll have to wait.

**Comment by SkeletalDemise** [comment]
The latest release is now on PyPI, do `pip install ciphey --upgrade` to get the latest version.
