### ISSUE TITLE
Add DNA codons decoder

### ISSUE THREAD

**Issue by lukasgabriel** [Ciphey/Ciphey#354]
https://www.dcode.fr/codons-genetic-code
https://en.wikipedia.org/wiki/Genetic_code
https://en.wikipedia.org/wiki/DNA_codon_table

**Comment by MikeMerz** [comment]
Hi,I'm new to contributing, is it possible to try this one?

**Comment by bee-san** [comment]
> Hi,I'm new to contributing, is it possible to try this one?

Hey @MikeMerz !! 

Welcome to Ciphey! And if you're new to contributing, what a great project to contribute to :wink: 

This is our guide on adding new things to Ciphey:

https://github.com/Ciphey/Ciphey/wiki/Adding-your-own-ciphers

You'll want to add a decoder for this.

I would suggest getting a function working outside of Ciphey first, and then importing it into Ciphey when it's ready to be added :)

if you have to have a dictionary or table of letters or an alphabet, please let us know. We can add it to CipheyDists which will be much easier for you and I to deal with :smile: 

We have a Discord where we can provide direct, as-soon-as-possible support too:
https://discord.gg/KfyRUWw

If you have any questions or need support please don't be afraid to let us know :) I have assigned this issue to you :sparkles:

**Comment by anantverma275** [comment]
Hello all,
I am new to Open Source contributions, so could you help me with what to do next?

I have already:
1. cloned this repository on my system
2. added **DNAtoBinary.py** file in **ciphey/basemods/Decoder**
3. configured **__init__.py** file accordingly by adding this module into the import list.

Also, could you tell me how do I test this module using the ciphey package?

Thank you!

**Comment by MikeMerz** [comment]
Hey @bee-san  ,
Thanks for the welcoming massage :)
I have written a class for the decoding according to the first comment, using a dictionary for the four letters of the DNA,
so after running some test I just commit the changes?

**Comment by bee-san** [comment]
> Hey @bee-san ,
> Thanks for the welcoming massage :)
> I have written a class for the decoding according to the first comment, using a dictionary for the four letters of the DNA,
> so after running some test I just commit the changes?

Hey! Very sorry, but someone got there first. This is especially annoying, as I assigned you to this issue and they must have ignored it :( #363 

I added another issue that I believe is quite easy to implement, do you want me to assign you to this instead? :) It's URL decoding

https://github.com/Ciphey/Ciphey/issues/368

**Comment by SkeletalDemise** [comment]
Hello, unfortunately this issue title is misleading and we are not looking for a DNA to Binary decoder. We are wanting a DNA codons decoder similar to this https://www.dcode.fr/codons-genetic-code
I'll fix it so it's not misleading and add more resources.

Additionally, I have now taken over this issue/decoder with additional support from @anantverma275 in the Discord. I have already created a table mapping the various DNA codons to letters. I suggest you pick another encoding or cipher to implement from one of the issues, or you can work on the one that @bee-san suggested. Thank you.

**Comment by MikeMerz** [comment]
> > Hey @bee-san ,
> > Thanks for the welcoming massage :)
> > I have written a class for the decoding according to the first comment, using a dictionary for the four letters of the DNA,
> > so after running some test I just commit the changes?
> 
> Hey! Very sorry, but someone got there first. This is especially annoying, as I assigned you to this issue and they must have ignored it :( #363
> 
> I added another issue that I believe is quite easy to implement, do you want me to assign you to this instead? :) It's URL decoding
> 
> #368

Ye sure I guess.
