### ISSUE TITLE
Add URL decoding

### ISSUE THREAD

**Issue by bee-san** [Ciphey/Ciphey#368]
### Problem:
URLs are encoded like so:
```
" " == "%20"
```

There are many more encodings other than space, this is just one example.

### Resources
https://www.w3schools.com/tags/ref_urlencode.ASP
https://www.urlencoder.org/
#### URL Decoding in Python
https://stackoverflow.com/questions/16566069/url-decode-utf-8-in-python
https://www.urldecoder.io/python/

Guide on how to add this to Ciphey here:
https://github.com/Ciphey/Ciphey/wiki/Adding-your-own-ciphers

**Comment by MikeMerz** [comment]
Hey @bee-san ,
Is it possible just to assign this issue to me?

**Comment by bee-san** [comment]
> Hey @bee-san ,
> Is it possible just to assign this issue to me?

Yes, sure!

**Comment by MikeMerz** [comment]
Hey,
A couple of questions: 
1)given the url, the decoded URL should be printed?
2)just making sure,given that coded URL contains % it may cause the module some problems
3)I tried running with "%.%" for reverse but after printing the table it doesn't stop,maybe its connected to 2

**Comment by bee-san** [comment]
> Hey,
> A couple of questions:
> 1)given the url, the decoded URL should be printed?
> 2)just making sure,given that coded URL contains % it may cause the module some problems
> 3)I tried running with "%.%" for reverse but after printing the table it doesn't stop,maybe its connected to 2

1. Given a string with the same encoding as URL encoding, decode that string and return it (the string may not be a URL, but it still might contain URL encoding)
2. % is not a problem for Ciphey anymore :) 
3. %.% does not pass any checkers, so Ciphey will never return that as plaintext :)

**Comment by MikeMerz** [comment]
OK,so if it's ready, to update I need to create a pull request?

**Comment by bee-san** [comment]
> OK,so if it's ready, to update I need to create a pull request?

Yup! To CipheyDists :D

**Comment by MikeMerz** [comment]
It's actually my first time, so i need to commint through pycharm to the master branch to someother branch that i should open and than opening the pull request?

**Comment by SkeletalDemise** [comment]
Closed by #400
