### ISSUE TITLE
/Library/Python/3.7/site-packages/cipheycore/_ciphey_core_py.so image not found

### ISSUE THREAD

**Issue by pezzivic** [Ciphey/Ciphey#373]
after installing ciphey on macOS 10.15.6 with python3 v3.7.3, I tried to run it and got the following error

Pez-MacBook-Pro:~ pez$ ciphey
Traceback (most recent call last):
  File "/usr/local/bin/ciphey", line 5, in <module>
    from ciphey.ciphey import main
  File "/Library/Python/3.7/site-packages/ciphey/__init__.py", line 1, in <module>
    from . import common
  File "/Library/Python/3.7/site-packages/ciphey/common.py", line 5, in <module>
    import cipheycore
  File "/Library/Python/3.7/site-packages/cipheycore/__init__.py", line 13, in <module>
    from . import _ciphey_core_py
ImportError: dlopen(/Library/Python/3.7/site-packages/cipheycore/_ciphey_core_py.so, 2): Library not loaded: /usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/Python
  Referenced from: /Library/Python/3.7/site-packages/cipheycore/_ciphey_core_py.so
  Reason: image not found

**Comment by SkeletalDemise** [comment]
Closing this because you didn't fill out the issue template and this is a duplicate issue. The documentation (https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions) lists this problem with Mac OS, and the solution is to install Docker and run Ciphey with it.
