### ISSUE TITLE
Make atbash a Cracker

### ISSUE THREAD

**Issue by Cyclic3** [Ciphey/Ciphey#377]
### Idea
Read the title

### Pros
Save a lot of time messing with loads of decodings from atbash

### Cons
This would mean that nesting ciphers inside atbash would not be detected without nested ciphers being explicitly enabled. It would also violate the general rule of "you need a key to be a cracker"

**Comment by bee-san** [comment]
@lukasgabriel I might steal this from you. I need to contribute to Cipheycore so I can learn how it works, so I can write documentation (similar to that of Decoding) for us :)

**Comment by lukasgabriel** [comment]
> @lukasgabriel I might steal this from you. I need to contribute to Cipheycore so I can learn how it works, so I can write documentation (similar to that of Decoding) for us :) 

Go right ahead :)

**Comment by SkeletalDemise** [comment]
I am closing this because I don't see any reason to make Atbash into a cracker. Since we are trying to get rid of CipheyCore and because Atbash doesn't have a key, and also doesn't return multiple results, I see no reason to make it into a cracker.
