### ISSUE TITLE
Requirement for 64bit to be listed on installation guide

### ISSUE THREAD

**Issue by XVXTOR** [Ciphey/Ciphey#380]
### Problem:
Ciphey doesn't seem to install on Windows + a 32 bit install of Python. Couldn't figure out why I was getting an error about a version not being found but the suggested fix was around Tensor flow and didn't work for me either.

### Solution:
Install 64bit of Python or use Docker.
I'm unable to add this to the Wiki as a pull request - perhaps it could be included on one of the landing pages?

**Comment by bee-san** [comment]
On it! :D

**Comment by bee-san** [comment]
@all-contributors please add @XVXTOR for documentation

**Comment by bee-san** [comment]
Done! :D
