### ISSUE TITLE
Spooky hex output for byte input

### ISSUE THREAD

**Issue by Cyclic3** [Ciphey/Ciphey#388]
**⚠️IMPORTANT⚠️ if you do not fill this out, we will automatically delete your issue. We will not help anyone that cannot fill out this template.**

- [x] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)

**Describe the bug**
Ciphey outputs random hex digit pairs when run on practically any ciphertext when set to bytes mode, and when the output is not redirected (i.e. into `less`)

**Plaintext**
**⚠️IMPORTANT⚠️ The below code is non-negotiable for "Ciphey didn't decrypt...." problems. If you do not tell us your plaintext, we will not help you.** 

```
hello, world
```
or any other string

**Version**
**⚠️IMPORTANT⚠️ We need this information because different environments will induce different bugs in Ciphey**
 - OS/Distro: Debian
 - Python version: Python 3.8.5
 - Ciphey versions: master (775fabe)
 - Did you use Docker? Nope

**Verbose Output**
**⚠️IMPORTANT⚠️ Verbose output will tell us why it's not working the way we expected it to be.**
https://pastebin.com/Gg41gpgU

**To Reproduce**

```
$ ciphey -t "hello, world" -b -C regex -p regex.regex=random_unmatchable_text
6c
6d
6c
6e
6c
6b
6c
6f
6c
73
6c
71
6c
72
6c
24
6c
79
72
73
72
70
72
75
72
71
72
6d
72
6f
72
6c
72
3a
72
67
....
```

**Expected behavior**
No spooky hex

**Any other information?**
Nope

**Comment by Cyclic3** [comment]
This is all in the ascii range (lmlnlklolslqlrl$lyrsrprurqrmrorlr:rg)

**Comment by Ozzyz** [comment]
This should be closed, since this is no longer the case in the master branch of CipheyCore. It is however still in `v.0.3.1`, and is as far as I can see due to the following snippet https://github.com/Ciphey/CipheyCore/blob/d7c7725bba90971e9757be1f039403c9e935ec71/include/ciphey/swig.hpp#L190-L195

**Comment by Ozzyz** [comment]
Also, a quick way to ensure that this code path is the one leading to this issue is to create a small `py` file anywhere in the Ciphey project with the following:
```
import cipheycore
plaintext = "AA".encode()
candidate_key = 0x00
cipheycore.xor_single_decrypt(plaintext, candidate_key)
``` 
By running this file you can observe the random hex output

**Comment by Ozzyz** [comment]
@bee-san , @Cyclic3 - should this be closed as it is no longer in CipheyCore master? Also, this is/was a problem related to CipheyCore, not Ciphey itself.

**Comment by SkeletalDemise** [comment]
@Cyclic3 this bug is still an issue because CipheyCore hasn't been updated and is still on 0.3.1. Can you release CipheyCore 0.3.2 on PyPI? Thank you.

**Comment by Cyclic3** [comment]
Release

**Comment by SkeletalDemise** [comment]
This is fixed now.
