### ISSUE TITLE
Feature request: Soundex

### ISSUE THREAD

**Issue by virtadpt** [Ciphey/Ciphey#412]
### Problem:
I think it would be eventually useful to detect and encode/decode Soundex (https://en.wikipedia.org/wiki/Soundex) encoding of phonetic words (i.e., "Robert" == "R163").

### Solution:
There are probably Soundex modules for Python out there, it should be possible to integrate one into the encoding detector as well as in a cracker.

**Comment by bee-san** [comment]
Hey Hackers of this spoopy month! 👻 
Welcome to the Ciphey repo(s)!
This issue requires you to add a decoder.

This wiki section walks you through EVERYTHING you need to know, and we've added some more links at the bottom of this issue to detail more about the decoder.
https://github.com/Ciphey/Ciphey/wiki#adding-your-own-crackers--decoders

**Comment by Ozzyz** [comment]
I'll take a stab at this : )

**Comment by sashreek1** [comment]
I would love to take up this issue :)

**Comment by HexChaos** [comment]
> I would love to take up this issue :)

Go ahead @sashreek1

**Comment by sashreek1** [comment]
Here's the problem  : 
As you already know a single soundex code can mean several different things. The example u gave of the word `Robert` (R163) is also the code for 
report | revert | Robert | Rupert | rapport | rebirth | reports | revered | reverts | Roberta | Roberto | Roberts | rapports | rebirths | reburied | refereed
and many more. Which means deciding it as a single word can be difficult.
Predicting possible words would probably require an AI model.
The best one i found was from wolframalpha which is unfortunately paid. 
Do y'all have any suggestions ?

**Comment by SkeletalDemise** [comment]
It will have to be a python cracker like T9. Then it can return multiple results so that Ciphey can figure out what combination is the best. You just need to make a dictionary that maps all the soundex codes to possible English words. This and T9 will be on hold though until we get a better English dictionary as the one that we currently have in CipheyDists is not that good. Issue for a better dictionary here: https://github.com/Ciphey/Ciphey/issues/438

**Comment by sashreek1** [comment]
yeah a cracker seems perfect. I'll also be on the look out for a good English dictionary.

**Comment by sashreek1** [comment]
Hey! am I supposed to be assigned to this issue so i can get back to it later ?

**Comment by bee-san** [comment]
I assigned you! :)
