### ISSUE TITLE
Add DTMF decoder

### ISSUE THREAD

**Issue by SkeletalDemise** [Ciphey/Ciphey#424]
https://www.dcode.fr/dtmf-code
https://en.wikipedia.org/wiki/Dual-tone_multi-frequency_signaling

**Comment by stanislavkocan** [comment]
Hi, I would like to contribute to this issue if possible :) I have alredy joined your Discord server too (stanislav). Can you please assign it to me ?

**Comment by bee-san** [comment]
> Hi, I would like to contribute to this issue if possible :) I have alredy joined your Discord server too (stanislav). Can you please assign it to me ?

Hey! We have already implemented this, however we will let you know about future encoders :)
