### ISSUE TITLE
Create CI testing to test Ciphey in the terminal

### ISSUE THREAD

**Issue by bee-san** [Ciphey/Ciphey#429]
### Problem:
Right now, Ciphey's tests run by importing Ciphey and checking the output.

Ciphey had a bug that only existed when we ran Ciphey in the terminal, not via an import.

### Solution:
Create CI (using TravisCI or GitHub actions) that `pip3 install ciphey` and then runs Ciphey with some tests, such as:

```
ciphey -q -t "hello"
```

The `-q` makes the output greppable, With this flag you can then capture the result of the terminal command and check to see if the results match.

So the algorithm looks like this:
(in CI such as TravisCI or GitHub actions using a Terminal -- no imports)
1. `pip3 install ciphey`
2. `ciphey -q -t <test_text>` (generate your own test text if you can. Choose an English sentence and use one of [these](https://github.com/Ciphey/Ciphey/wiki/Supported-Ciphers).
3. Check output to make sure the decrypted text matches the plaintext.
4. If no errors, make the CI pass (I think you have to return an OS status code for this?)

**Comment by malathit** [comment]
Shall I work on this for the hacktoberfest?

**Comment by bee-san** [comment]
> Shall I work on this for the hacktoberfest?
> 
> Also I have a few more questions on this? Say I want to achieve this with github actions, should I write a test for each OS like Ubuntu(Linux), Windows, MacOs?

Hey!

Just Ubuntu, Linux is okay. We can't test on Windows very well, and we can assume if it works on Linux it works on Mac OS due to our other CI.

And sure, you can work on this for hacktoberfest :partying_face: I'll assign it to you! Are you in the DIscord? :smile:

**Comment by malathit** [comment]
Thanks for assigning. yes, I am on discord.
