### ISSUE TITLE
Add Baconian decoder

### ISSUE THREAD

**Issue by SkeletalDemise** [Ciphey/Ciphey#432]
Hey Hackers of this spoopy month! 👻 
Welcome to the Ciphey repo(s)!
This issue requires you to add a decoder.

This wiki section walks you through EVERYTHING you need to know, and we've added some more links at the bottom of this issue to detail more about the decoder.
https://github.com/Ciphey/Ciphey/wiki#adding-your-own-crackers--decoders

https://www.dcode.fr/bacon-cipher
https://en.wikipedia.org/wiki/Bacon%27s_cipher
There are two variants of the Baconian cipher. One where I=J and U=V and one where every letter has it's own distinct code. Ciphey should be able to decode both.

**Comment by imtira** [comment]
I can take this one on. Can I get assigned?

**Comment by DhrubojyotiBis1** [comment]
Hi, @SkeletalDemise I would like to work on this issue. Can you assign it to me?

**Comment by bee-san** [comment]
> Hi, @SkeletalDemise I would like to work on this issue. Can you assign it to me?

Done!
