### ISSUE TITLE
Add UUencode decoder

### ISSUE THREAD

**Issue by SkeletalDemise** [Ciphey/Ciphey#433]
Hey Hackers of this spoopy month! 👻 
Welcome to the Ciphey repo(s)!
This issue requires you to add a decoder.

This wiki section walks you through EVERYTHING you need to know, and we've added some more links at the bottom of this issue to detail more about the decoder.
https://github.com/Ciphey/Ciphey/wiki#adding-your-own-crackers--decoders

https://www.dcode.fr/uu-encoding
https://en.wikipedia.org/wiki/Uuencoding

**Comment by stanislavkocan** [comment]
I would like to solve this issue. Can you please assign it to me ?

**Comment by bee-san** [comment]
> I would like to solve this issue. Can you please assign it to me ?

Done! :)

**Comment by bee-san** [comment]
This issue is now open again! :D

**Comment by malathit** [comment]
Hey @bee-san, I would like to give it a try. Can you please assign this to me?

**Comment by bee-san** [comment]
Done! :D @malathit
