### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Unviray** [Ciphey/Ciphey#436]
I'm asking if it's possible to translating the README in _French_.  
Or any part of the package.  
I just want to make a _pull request_ for the _Hacktoberfest_ event.

**Comment by bee-san** [comment]
Hey! A french translation is fine by us :D

**Comment by laenNoCode** [comment]
hey ! i can work on it. I'm a native french speaker

**Comment by SkeletalDemise** [comment]
Closing this because it's old and we have a French translation [now.](https://github.com/Ciphey/Ciphey/blob/master/translations/fr/README.md)
