### ISSUE TITLE
Small improvements to the code base

### ISSUE THREAD

**Issue by jacobggman** [Ciphey/Ciphey#437]
### Idea
Make small improvements to the code base.

* Remove commented code (https://github.com/Ciphey/Ciphey/blob/b46e00c611ee4b5f5795e967a50b05a63cbb5ef0/ciphey/ciphey.py#L242) 

* Fix the order of the metheds in classes of Decoders like the order of the example of "Adding a decoder" (Should be the last method and not first: https://github.com/Ciphey/Ciphey/blob/b46e00c611ee4b5f5795e967a50b05a63cbb5ef0/ciphey/basemods/Decoders/leet.py#L11-L13)

Can I do that?

### Pros
Make the code base cleaner and more organized

### Cons
None

**Comment by bee-san** [comment]
Hey! Feel free to make a PR.

For:

> Fix the order of the metheds in classes of Decoders like the order of the example of "Adding a decoder" (Should be the last method and not first: 

Why would you suggest this? :)

**Comment by jacobggman** [comment]
I think like that it will be cleaner, more organize and more easy to find the functions

**Comment by bee-san** [comment]
> I think like that it will be cleaner, more organize and more easy to find the functions

Sure! Make the PR :D

**Comment by jacobggman** [comment]
@bee-san Should I delete the logs (`logger`) in the Decoders?
