### ISSUE TITLE
Add Braille Decoder

### ISSUE THREAD

**Issue by bee-san** [Ciphey/Ciphey#439]
Hello spoooopyyy hackers :jack_o_lantern: 

This is a Hacktoberfest only issue! :ghost: 

Find our contributing guidelines here, this walks you through how to add a decoder / cracker! 
https://github.com/Ciphey/Ciphey/wiki#adding-your-own-crackers--decoders

Don't worry if it looks hard, we will walk you through everything! :) 

**Write this issue in Python!**

# Links
These links will help you understand how this works!

https://stackoverflow.com/questions/41922629/convert-text-to-braille-unicode-in-python
https://github.com/markomanninen/pybrl (this is very old)

**Comment by rogercyyu** [comment]
Hey, can I try to do this in Python? I am new to open-source.

**Comment by bee-san** [comment]
> Hey, can I try to do this in Python? I am new to open-source.

Yes! Go right ahead <3 And welcome to open source! 

We have a Discord where you can talk directly to us in real time too, it's on our wiki :D

**Comment by Trisanu-007** [comment]
Can I work on this please?

**Comment by Trisanu-007** [comment]
@rogercyyu I would like to work together. Can we discuss it further on discord?

**Comment by rogercyyu** [comment]
@Trisanu-007 What's your discord?

**Comment by Trisanu-007** [comment]
@rogercyyu are you in the discord grp of Ciphy .... if yes whats your username?

**Comment by rogercyyu** [comment]
@Trisanu-007 yeah, hiddenhazard#0965
