### ISSUE TITLE
Add Docker

### ISSUE THREAD

**Issue by DanBrown47** [Ciphey/Ciphey#448]
### Problem:
Adding a docker is a good move as we can run this in containerized mode and will be mature as an official app

### Solution:
A docker file will solve the problem

**Comment by HexChaos** [comment]
This project is already on Docker
https://hub.docker.com/r/remnux/ciphey/dockerfile

**Comment by bee-san** [comment]
As Hex has said, we are on Docker. We would like our own Dockerfile with docker organisation though, but that depends entirely on if anyone is willing to help us with that :)
