### ISSUE TITLE
Add support for Base64 + Gzip 

### ISSUE THREAD

**Issue by yihong0618** [Ciphey/Ciphey#519]
### Problem:
Hi~
When I use ciphey I try to decode this code belowe
```
ciphey -t H4sIAAAAAAAAE4vmUlCoBmIFBaW0nMT0YiUFK4VoLrBArA5EPLM4ILG0OBUkk5aYU5wKFU5KTSwpDkgt8s3MKy0ByxoaW0LlSjJzU4tLEnMLQMIWJmZIwo4VmcVQUaBgrc5wst/EHJv9RoZm2BwAEqa+C8ywusAYaxCAhEl3QUlRKckOMLa0wOYAkDDIAVyxAL55HNeHAgAA
```
![image](https://user-images.githubusercontent.com/15976103/97242359-a2926f00-182e-11eb-8cba-f102832a0518.png)

The ciphey  only show its `Base`

But I It’s a base64 encoded zipped string. when it starts something like `H4sIAAAAAAA.........`

![image](https://user-images.githubusercontent.com/15976103/97242988-3ca6e700-1830-11eb-861c-fdccd41311bc.png)

Another example from stackoverflow https://stackoverflow.com/questions/43904605/decompress-gz-compressed-string-using-python3-6

Can `Ciphey` support this kind of string decode ?

**Comment by bee-san** [comment]
That's an ancient version of Ciphey (2+ years old). Please use the latest version :)

**Comment by yihong0618** [comment]
@bee-san Thanks a lot. I will update right now.
