### ISSUE TITLE
Ciphey cannot solve this "QlJVSCBNT01FTlQgTE1BTw==" base64 message

### ISSUE THREAD

**Issue by DrPleaseRespect** [Ciphey/Ciphey#541]
**⚠️IMPORTANT⚠️ if you do not fill this out, we will automatically delete your issue. We will not help anyone that cannot fill out this template.**

- [X] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)

**Describe the bug**
I don't know if this is a bug but Ciphey can't decrypt this simple base64 message that i generated with python.
using this code.. i haven't tried using online base64 generators so i don't know if it only happens with python.
```python
base64_message = input().encode('ascii')
message = base64.b64decode(base64_message).decode('ascii')
```

**Plaintext**
**⚠️IMPORTANT⚠️ The below code is non-negotiable for "Ciphey didn't decrypt...." problems. If you do not tell us your plaintext, we will not help you.** 

```
QlJVSCBNT01FTlQgTE1BTw== 
```
**Version**
**⚠️IMPORTANT⚠️ We need this information because different environments will induce different bugs in Ciphey**
 - OS/Distro: Windows 10 Version 2004 (OS Build 19041.572)
 - Python version: Python 3.7.0
 - Ciphey versions: ciphey Version 5.6.0 | cipheycore Version 0.3.1 | cipheydists Version 0.3.31
 - Did you use Docker? No

**Verbose Output**
**⚠️IMPORTANT⚠️ Verbose output will tell us why it's not working the way we expected it to be.**
Verbose Output
[ciphey -vvv -t "QlJVSCBNT01FTlQgTE1BTw=="](https://gist.github.com/DrPleaseRespect/53ddbeccee9a5ae883cf9a1188c47ebd)
[ciphey -vvv](https://gist.github.com/DrPleaseRespect/8e5658e4ea1134702da9c683e11bc213)

**To Reproduce**
1. Terminal Input. Not using a text file.
2. -t "QlJVSCBNT01FTlQgTE1BTw=="

**Expected behavior**

I expected it to show this message
```
BRUH MOMENT LMAO
```
as a test.

**Any other information?**
using the verbose flag
i saw that in the ciphey.basemods.Decoders.bases:_dispatch:16 and the ciphey.basemods.Decoders.unicode:decode:19 lines
it was able to decrypt the message. but it didn't prompt and ask if it was the right answer.
the process got stuck at ciphey.basemods.Searchers.ausearch:search:263 - At depth 5

**Comment by SkeletalDemise** [comment]
This is an issue with Ciphey's checkers, as Ciphey can decode it if you use regex: `ciphey -t "QlJVSCBNT01FTlQgTE1BTw==" -C regex -p regex.regex=MOMENT`

I think it's because your string is too short, and it doesn't get caught by Ciphey's checkers. It also seems like Ciphey doesn't consider "BRUH" and "LMAO" to be English. If you Base64 encode "WOW MOMENT LMAO" and try it, it works and Ciphey decodes it.

**Comment by SkeletalDemise** [comment]
This is fixed now with the new quadgrams checker. Running `ciphey -t "QlJVSCBNT01FTlQgTE1BTw=="` works successfully.
