### ISSUE TITLE
will hashes usable in future?

### ISSUE THREAD

**Issue by gamersover** [Ciphey/Ciphey#543]
Noticed that `Hashes are turned off right now due to some bugs with external services we cannot control.`，so will hashes usable in future? Or how can i turn it on? Thank you.

**Comment by SkeletalDemise** [comment]
Support for hashes will be available in the future. I know that @bee-san was working on hash support with a forked version of HashID to identify hashes and John the Ripper and/or HashCat to crack hashes. We'll also support API keys for hash lookups. It's very exciting but you'll have to wait for now.

**Comment by gamersover** [comment]
Thanks for your reply
