### ISSUE TITLE
Ciphey ImportError

### ISSUE THREAD

**Issue by MrKomodoDragon** [Ciphey/Ciphey#544]
**⚠️IMPORTANT⚠️ if you do not fill this out, we will automatically delete your issue. We will not help anyone that cannot fill out this template.**

- [x] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)

**Describe the bug**
When I attempt to run `ciphey -t 6369636164612033333031`, it gives my an ImportError. 

**Plaintext**
**⚠️IMPORTANT⚠️ The below code is non-negotiable for "Ciphey didn't decrypt...." problems. If you do not tell us your plaintext, we will not help you.** 

```
6369636164612033333031 
```
**Version**
**⚠️IMPORTANT⚠️ We need this information because different environments will induce different bugs in Ciphey**
 - OS/Distro: macOS Catalina
 - Python version: Python 3.8.5
 - Ciphey versions: Ciphey: 5.10.0, CipheyCore: 0.3.2, CipheyDists: 0.3.33
 - Did you use Docker? Yes

**Verbose Output**
**⚠️IMPORTANT⚠️ Verbose output will tell us why it's not working the way we expected it to be.**
Here is the [GitHub Gist](https://gist.github.com/MrKomodoDragon/dc4add12762310b379e7632d4df54401)

**To Reproduce**
1. What input did you use?
I used a string of text: `6369636164612033333031 `
2. What flags / arguments did you use?
I used `-t`. 
**Expected behavior**
I expected it to decode this number sequence. 

**Any other information?**
I installed this via Docker.

**Comment by saurabh-nagre** [comment]
When i started to use ciphey first time and want to run:
```
from ciphey import decrypt
from ciphey.iface import Config

res = decrypt(
        Config().library_default().complete_config(),
        "SGVsbG8gbXkgbmFtZSBpcyBiZWUgYW5kIEkgbGlrZSBkb2cgYW5kIGFwcGxlIGFuZCB0cmVl",
    )
```

it giving me error as:
**ImportError: cannot import name 'decrypt' from partially initialized module 'ciphey' (most likely due to a circular import)**

I downloaded it from python version 3.8.5
pip version 21.2.4

**Comment by SkeletalDemise** [comment]
I'm closing this because that error comes from trying to install and run Ciphey via pip on MacOS. You said you installed it through Docker but `ciphey -t "6369636164612033333031"` isn't how you run it with Docker. You need to run it like `docker run -it --rm remnux/ciphey -t "6369636164612033333031"` for example.
Also if you don't want to use Docker you can install Ciphey on MacOS via Homebrew or MacPorts.
