### ISSUE TITLE
morse code cannot detect

### ISSUE THREAD

**Issue by vivienicepig** [Ciphey/Ciphey#548]
### Problem:
easy morse code like
test
. .- ... -.-- -- --- .-. ... .
cannot detect

**Comment by Itamikame** [comment]
your morse code is without a space between easy and morse thats why it doesnt detect it
if you use 
`. .- ... -.-- / -- --- .-. ... .`
it works without any problems

**Comment by SkeletalDemise** [comment]
This isn't a problem with the Morse code decoder. It's because the final result has no spaces between the words. This is a problem with Ciphey's checkers. A checker for English with no spaces is being worked on. This should be fixed soon.

**Comment by iNTELIex** [comment]
I agree it should be fixed.

**Comment by SkeletalDemise** [comment]
This can't be fixed. Even with the new quadgrams checker it doesn't work. `EASYMORSE` is simply too short of a plaintext to identify. Use a longer sentence to test Ciphey with.
