### ISSUE TITLE
When install python3.9 with pyenv in macOS, something wrong report.

### ISSUE THREAD

**Issue by Kilala-Z** [Ciphey/Ciphey#566]
**⚠️IMPORTANT⚠️ if you do not fill this out, we will automatically delete your issue. We will not help anyone that cannot fill out this template.**

- [✅ ] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)

**Describe the bug**
I install python3.9 with pyenv, when I try exec ciphey, an error report.

**Plaintext**
**⚠️IMPORTANT⚠️ The below code is non-negotiable for "Ciphey didn't decrypt...." problems. If you do not tell us your plaintext, we will not help you.** 

```
 ciphey -p ausearch.enable_nested=True -t "GOWOKGFOTRSERRAUVRFFBFCAAWWAWGTWWQGJFMWBTKFTJASFAEZTZWIMDZRYFPZRATMLGFYDROWRBWLXKGQHGQWQXWLKQYCQOMFCUVJFQVFQTUIECCGDKTZVVJEJBG"                
Traceback (most recent call last):
  File "/Users/hostname/.pyenv/versions/3.9.0/bin/ciphey", line 5, in <module>
    from ciphey.ciphey import main
  File "/Users/hostname/.pyenv/versions/3.9.0/lib/python3.9/site-packages/ciphey/__init__.py", line 1, in <module>
    from . import common
  File "/Users/hostname/.pyenv/versions/3.9.0/lib/python3.9/site-packages/ciphey/common.py", line 5, in <module>
    import cipheycore
  File "/Users/hostname/.pyenv/versions/3.9.0/lib/python3.9/site-packages/cipheycore/__init__.py", line 13, in <module>
    from . import _ciphey_core_py
ImportError: dlopen(/Users/hostname/.pyenv/versions/3.9.0/lib/python3.9/site-packages/cipheycore/_ciphey_core_py.so, 2): Library not loaded: /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/Python
  Referenced from: /Users/hostname/.pyenv/versions/3.9.0/lib/python3.9/site-packages/cipheycore/_ciphey_core_py.so
  Reason: image not found
```
**Version**
**⚠️IMPORTANT⚠️ We need this information because different environments will induce different bugs in Ciphey**
 - OS/Distro: macOS
 - Python version: python3.9.0
 - Ciphey versions: ciphey 5.11.0, cipheycore 0.3.2, cipherdists 0.3.34
 - Did you use Docker? No

**Verbose Output**
**⚠️IMPORTANT⚠️ Verbose output will tell us why it's not working the way we expected it to be.**
Run Ciphey with `ciphey -vvv` and paste the results into [Pastebin.com](https://pastebin.com) or a [GitHub Gist](https://gist.github.com/)

Verbose output is the same as the plaintext.

**To Reproduce**
1. What input did you use?
2. What flags / arguments did you use?

**Expected behavior**

**Any other information?**

**Comment by SkeletalDemise** [comment]
I'm closing this issue because as explained on our [Common Issues & Their Solutions](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions) page, Ciphey doesn't currently work on MacOS without using Docker.
