### ISSUE TITLE
Ciphey-3.0.5.dist-info is installed instead of the package 

### ISSUE THREAD

**Issue by johnny125** [Ciphey/Ciphey#573]
I read the whole documentation and installation guide along with the issues but I could not find a solution or an explanation to my problem : 

I installed Ciphey on windows 10 64 bit and followed the installation instruction as written in this page :

https://github.com/Ciphey/Ciphey/wiki/Installation

I have python 3.9 and pip 20.0.7 . My python is an 64 bit version : 

python -c "import sys; print(sys.version)":

3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]

I executed this command in CMD :

python -m pip install -U pip 

then I got :

C:\windows\system32>python -m pip install -U ciphey
Collecting ciphey
  Using cached ciphey-5.10.0-py3-none-any.whl (87 kB)
Requirement already satisfied: click<8.0.0,>=7.1.2  (from ciphey) (7.1.2)
  Using cached ciphey-5.9.0-py3-none-any.whl (84 kB)
  Using cached ciphey-5.8.0-py3-none-any.whl (77 kB)
  Using cached ciphey-5.7.0-py3-none-any.whl (74 kB)
  Using cached ciphey-5.6.0-py3-none-any.whl (72 kB)
  Using cached ciphey-5.5.3-py3-none-any.whl (70 kB)
  Using cached ciphey-5.5.2-py3-none-any.whl (69 kB)
  Using cached ciphey-5.4.0-py3-none-any.whl (66 kB)
  Using cached ciphey-5.3.2-py3-none-any.whl (58 kB)
  Using cached ciphey-5.3.1-py3-none-any.whl (58 kB)
  Using cached ciphey-5.3.0-py3-none-any.whl (56 kB)
  Using cached ciphey-5.2.0-py3-none-any.whl (54 kB)
  Using cached ciphey-5.1.0-py3-none-any.whl (51 kB)
  Using cached ciphey-5.0.0-py3-none-any.whl (50 kB)
  Using cached ciphey-4.2.1-py3-none-any.whl (38 kB)
  Using cached ciphey-4.2.0-py3-none-any.whl (37 kB)
  Using cached Ciphey-3.8.2-py3-none-any.whl (6.2 MB)
  Using cached Ciphey-3.8.1-py3-none-any.whl (6.2 MB)
  Using cached Ciphey-3.8-py3-none-any.whl (6.2 MB)
  Using cached ciphey-3.5.9-py3-none-any.whl (37 kB)
  Using cached Ciphey-3.5.7-py3-none-any.whl (6.2 MB)
  Using cached Ciphey-3.0.7-py3-none-any.whl (6.1 MB)
  Using cached Ciphey-3.0.6-py3-none-any.whl (6.1 MB)
  Using cached Ciphey-3.0.5-py3-none-any.whl (43 kB)
Installing collected packages: ciphey
Successfully installed ciphey-3.0.5

However all what I got is : 

Ciphey-3.0.5.dist-info in which there are : 

INSTALLER 1kb

METADATA 1kb

RECORD 6kb

REQUESTED 0kb

Top-level.txt 1kb

WHEEL 1kb

I cannot execute these files and I cannot run Ciphey through these files . I am confused . Help

**Comment by SkeletalDemise** [comment]
Ciphey 3.0.5 is an extremely old version. I'm not sure why it installed that version instead of the newest. Try running `pip install ciphey==5.10.0`. After that, you should be able to run ciphey like this for example: `ciphey -t "VGhpcyBpcyBhbiBleGFtcGxl"`

**Comment by johnny125** [comment]
Hello , Thank you for your reply . I tried the command you write me : **pip install ciphey==5.10.0** . However it gives this error : 

**ERROR: Could not find a version that satisfies the requirement cipheycore<0.4.0,>=0.3.2 (from ciphey)
ERROR: No matching distribution found for cipheycore<0.4.0,>=0.3.2**

**Comment by SkeletalDemise** [comment]
Ah, Ciphey doesn't work with Python 3.9 currently. You'll need to use either Python 3.7 or Python 3.8 64 bit.

**Comment by johnny125** [comment]
Thank you very much 👍 :)

**Comment by SkeletalDemise** [comment]
Closing this because it was due to using Python 3.9 on Windows which isn't supported.
