### ISSUE TITLE
'module' object is not callable

### ISSUE THREAD

**Issue by asjdf** [Ciphey/Ciphey#577]
>  ciphey -t "5piv55qE5piv55qECiA="

> Traceback (most recent call last):
>   File "c:\users\24385\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\users\24385\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\24385\AppData\Local\Programs\Python\Python37\Scripts\ciphey.exe\__main__.py", line 7, in <module>
>   File "c:\users\24385\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "c:\users\24385\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "c:\users\24385\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "c:\users\24385\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "c:\users\24385\appdata\local\programs\python\python37\lib\site-packages\ciphey\ciphey.py", line 261, in main
>     with yaspin(Spinners.earth, "Thinking") as sp:
> TypeError: 'module' object is not callable

```
Include your plaintext here, replacing this 
```
**Version**
**⚠️IMPORTANT⚠️ We need this information because different environments will induce different bugs in Ciphey**
 - OS/Distro: Windows10
 - Python version: Python 3.7.8
 - Ciphey versions: ciphey 5.11.0
 - Did you use Docker? No.

**Verbose Output**
[Pastebin](https://pastebin.com/bHg4MRc8)

**To Reproduce**
1. What input did you use?
 ciphey -t "5piv55qE5piv55qECiA="
2. What flags / arguments did you use?
 base64

**Comment by Itamai** [comment]
I dont get the error for me it is stuck at the thinking process because ciphey only can detect english text/words

**Comment by Apocsword** [comment]
Need to learn more languages

**Comment by asjdf** [comment]
> I dont get the error for me it is stuck at the thinking process because ciphey only can detect english text/words

ciphey -t "amRm"
Traceback (most recent call last):
  File "c:\users\24385\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\24385\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\24385\AppData\Local\Programs\Python\Python37\Scripts\ciphey.exe\__main__.py", line 7, in <module>
  File "c:\users\24385\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\24385\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\24385\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\24385\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\24385\appdata\local\programs\python\python37\lib\site-packages\ciphey\ciphey.py", line 261, in main
    with yaspin(Spinners.earth, "Thinking") as sp:
TypeError: 'module' object is not callable

it is base64 English text

**Comment by MisakaNatsu** [comment]
look for this file :site-packages/ciphey/ciphey.py
change the line"import yaspin" to "from yaspin import yaspin"
then try again.

**Comment by MisakaNatsu** [comment]
a update led to this problem

**Comment by SkeletalDemise** [comment]
I'm going to close this. This error is because Ciphey version 5.11.0 is broken and it was pulled from PyPI a while ago. Run the command `pip install ciphey==5.10.0` to downgrade to version 5.10.0 to fix it. Once we release the next version, this will be fixed so it will no longer install 5.11.0.
