### ISSUE TITLE
TypeError: Multiple inheritance with NamedTuple is not supported

### ISSUE THREAD

**Issue by 7Ragnarok7** [Ciphey/Ciphey#579]
**⚠️IMPORTANT⚠️ if you do not fill this out, we will automatically delete your issue. We will not help anyone that cannot fill out this template.**

- [x] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)

**Describe the bug**
I am getting the following error when I run ciphey :
```
Traceback (most recent call last):
  File "/usr/local/bin/ciphey", line 5, in <module>
    from ciphey.ciphey import main
  File "/usr/local/lib/python3.9/dist-packages/ciphey/__init__.py", line 3, in <module>
    from . import iface
  File "/usr/local/lib/python3.9/dist-packages/ciphey/iface/__init__.py", line 1, in <module>
    from ._config import Config
  File "/usr/local/lib/python3.9/dist-packages/ciphey/iface/_config.py", line 21, in <module>
    from ._modules import Checker, Searcher, ResourceLoader, PolymorphicChecker
  File "/usr/local/lib/python3.9/dist-packages/ciphey/iface/_modules.py", line 225, in <module>
    class CrackResult(NamedTuple, Generic[T]):
  File "/usr/lib/python3.9/typing.py", line 1876, in _namedtuple_mro_entries
    raise TypeError("Multiple inheritance with NamedTuple is not supported")
TypeError: Multiple inheritance with NamedTuple is not supported

```
**Plaintext**
**⚠️IMPORTANT⚠️ The below code is non-negotiable for "Ciphey didn't decrypt...." problems. If you do not tell us your plaintext, we will not help you.** 

```
Include your plaintext here, replacing this 
```
**Version**
**⚠️IMPORTANT⚠️ We need this information because different environments will induce different bugs in Ciphey**
 - OS/Distro: Kali Linux
 - Python version: 3.9.1
 - Ciphey versions: 5.10.0
 - Did you use Docker? No.

**Verbose Output**
**⚠️IMPORTANT⚠️ Verbose output will tell us why it's not working the way we expected it to be.**
Run Ciphey with `ciphey -vvv` and paste the results into [Pastebin.com](https://pastebin.com) or a [GitHub Gist](https://gist.github.com/)

**To Reproduce**
```
ciphey --help
```
**Expected behavior**

**Any other information?**

**Comment by SkeletalDemise** [comment]
The error is because you are using Python 3.9. Ciphey currently only works with Python 3.7 and Python 3.8. You'll need to downgrade to use Ciphey. We are trying to make Ciphey support Python 3.9.

**Comment by 7Ragnarok7** [comment]
Oh okay. Thanks for the information ^_^ 
Closing the issue.
