### ISSUE TITLE
Make lazy-object-proxy>=1.5.2 in requirements.txt and change code in similar way

### ISSUE THREAD

**Issue by machinexa2** [Ciphey/Ciphey#580]
Make lazy-object-proxy>=1.5.2 in requirements.txt and change code in similar way
Close this issue when done.

**Comment by SkeletalDemise** [comment]
Can you explain what you mean? We don't have a requirements.txt anymore as it wasn't needed. `lazy-object-proxy` also isn't in pyproject.toml and it doesn't look like we import it anywhere in Ciphey.

**Comment by machinexa2** [comment]
Looks like its a issue of astroid module rather than ciphey

**Comment by machinexa2** [comment]
sorry for inconvenience
