### ISSUE TITLE
pip! cannot find cipheycore.

### ISSUE THREAD

**Issue by HumanCodingMachine** [Ciphey/Ciphey#581]
I'm continually trying to install Ciphey, yet I'm unable to do so due to a dependency error. 

Error:

ERROR: Could not find a version that satisfies the requirement cipheycore<0.4.0,
>=0.3.2 (from ciphey) (from versions: 0.0.1)
ERROR: No matching distribution found for cipheycore<0.4.0,>=0.3.2 (from ciphey)

**Comment by SkeletalDemise** [comment]
I'm closing this because you didn't fill out the Issue template.
