### ISSUE TITLE
Rework of Neural Network

### ISSUE THREAD

**Issue by brandonskerritt** [Ciphey/Ciphey#61]
* [ ] - Larger text corpus. Explore using English Wikipedia, Reddit comments, British National Corpus of Quantum Stat datasets
* [ ] - Build the text corpus into an actual data set hosted on Kaggle or the likes. 
* [ ] - Change what Ciphey's NN trains on. Add in these:
    * [ ] - "=" since basees use it, it'll help Ciphey identify bases easier.
    * [ ] - Spaces, since some encryption methods do not use spaces.
    * [ ] - Puncuation, as some encryptions use puncuation
    * [ ] - Length of text
    * [ ] - Range of letters / numbers
* [ ] - Explore using FOREST instead of a DNN.
* [ ] Use manual REGEX to check some things for encodings

**Comment by Cyclic3** [comment]
We no longer use a neural net
