### ISSUE TITLE
Docker link on README doesn't point to docker hub

### ISSUE THREAD

**Issue by mohzulfikar** [Ciphey/Ciphey#615]
### Idea
_What exactly do you want to do?_
The link on README for docker (universal) points to PyPI instead of docker hub. Was this on purpose?

### Pros
_How would it help the code? Does it make things faster, or the code more maintainable?_
if it's not on purpose, then I want to fix it (it seems like the translation is also affected). So that it doesn't confuse the user.

### Cons
_Would this break anything? Would it mean a rewrite of all the code?_
As this contribution only modifies README, it would not break anything.

**Comment by bee-san** [comment]
Sure! If there's a dockerhub image submit a PR :)

**Comment by mohzulfikar** [comment]
Hi, thanks for the reply. I'll open the PR shortly.
