### ISSUE TITLE
Hai there, my distro have pip disabled , what to do?

### ISSUE THREAD

**Issue by C3x64** [Ciphey/Ciphey#616]
Hello there everyone, small disclaimer :read this if you're chill person, I am autistic and I trigger people with out knowing , I can't function in society with out annoying people or being constantly misinterpreted, so if you're pissy type, just ignore me please. 

### Problem:
Can't install pip, probably cause i'm stupid, and i don't like spending whole day troubleshooting , and mindlessly copy passing command lines, i followed all instructions at end I gave up since pip isn't supported by distribution I use apparently, so I can't download ciphey at all.

### Solution:
maybe upload this program on repository? If that's possible, I gave up after 3h, and it's shame since it looks cool, others are bloated but at least they work, well I can get them to work, i can't even give this one  a chance.

I will try latter, but It's pain for me, even if i am willing to learn new things, and research stuff, also idk how to express myself rn, so idk if anyone will understand what i am talking about, so in short:

pip not supported here, is possible to install this with out pip? dock containers made cpu go high, and result wasn't coming.

Thank you for reading, and apologies if message got you confused, I really tried.

**Comment by SkeletalDemise** [comment]
What distro are you using? It should be easy to install pip on most distros if it's not already installed. Also it would be easier to join the Discord to get help with installing Ciphey.

**Comment by bee-san** [comment]
@C3x64 :
> dock containers made cpu go high, and result wasn't coming.
See https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions#ciphey-runs-forever--cant-decrypt-this-input

For why this is happening 😄

**Comment by C3x64** [comment]
o thank you, also my distro is mint 19.3

I did installed pip but it bugged cinnamon session, needed to revert.
message was "pip is disabled something something warning"
