### ISSUE TITLE
Improve viginere & transposition

### ISSUE THREAD

**Issue by brandonskerritt** [Ciphey/Ciphey#67]
- [x] Viginere uses list slicing which creates a new lsit each time, VERY slow.
- [x] A chi-squared association test is good for transposition stuff you can use it to really quickly match distributions and shit
- [ ] Remeber that, with a viginere cipher, a key as long as the message is actually information theoretically secure https://en.m.wikipedia.org/wiki/Index_of_coincidence give users an option to choose to stop early or continue going on

**Comment by Cyclic3** [comment]
Most of this was done with the import of cipheycore
