### ISSUE TITLE
Incorporate codetective

### ISSUE THREAD

**Issue by MariasStory** [Ciphey/Ciphey#671]
This one seems to be an older repo:
https://github.com/blackthorne/Codetective

I was not sure if it belogs here or to pyWhat, this why I also pointen the repository there:
https://github.com/bee-san/pyWhat/issues/118

**Comment by MariasStory** [comment]
Interesting comment from @piatrashkakanstantinass:
https://github.com/bee-san/pyWhat/issues/118#issuecomment-881872754

Hi there 👋! It seems that you are looking for [name-that-hash](https://github.com/HashPals/Name-That-Hash). PyWhat used it in the past; however, currently, hashes are not supported by what.

**Comment by MariasStory** [comment]
I agree, and with what I see it from https://github.com/Ciphey/Ciphey/issues/625:

Ciphey is made up of many smaller projects:
Name-that-hash
...

**Comment by MariasStory** [comment]
Closing the issue.

**Comment by SkeletalDemise** [comment]
Yes you are right, this isn't the place for this. If you're looking for a hash identifier tool then you can try Name-that-hash. We also have a tool called Search-that-hash for looking up hashes which we're going to add to Ciphey. If you have any specific regexes that you want added that aren't hash types you can make an issue at the pyWhat repo: https://github.com/bee-san/pyWhat
