### ISSUE TITLE
Update install wiki page with correct Python dependency

### ISSUE THREAD

**Issue by gregsskyles** [Ciphey/Ciphey#689]
### Idea
Change the text on the install wiki page that says "Python 3.7 and above" to "Python 3.7-3.8"

See [#688](https://github.com/Ciphey/Ciphey/issues/688#issuecomment-918090472)

### Pros
It would have saved me a day or two of head-scratching and chasing false dependencies, and is more accurate.

### Cons
Nothing that I know of, unless Python 3.9 works on platforms other than Windows.

**Comment by SkeletalDemise** [comment]
>Nothing that I know of, unless Python 3.9 works on platforms other than Windows.

Ciphey does in fact work on Linux with Python 3.9. Windows is the main platform it doesn't work on with Python 3.9. Thank you, I updated the wiki. 👍

**Comment by gregsskyles** [comment]
Well that's annoying; one would have hoped that Python would be more platform-agnostic than that.
