### ISSUE TITLE
Complete Noob here just trying to run Ciphey - Python install and PIP good but nothing else works...

### ISSUE THREAD

**Issue by GearTester** [Ciphey/Ciphey#691]
C:\WINDOWS\system32>py
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> python3 -m pip install -U ciphey
  File "<stdin>", line 1
    python3 -m pip install -U ciphey
               ^
SyntaxError: invalid syntax

**Comment by Jayy001** [comment]
Hi,

Ciphey doesn't support version 3.9 - Please downgrade to 3.8 🙂

**Comment by GearTester** [comment]
Ty

**Comment by GearTester** [comment]
I did that now this
[image: Ciphy.PNG]

**Comment by GearTester** [comment]
I got it working, but it seem to just think then... neve display results any ideas?

**Comment by Jayy001** [comment]
Hey, I can't seem to see the image. If it's stuck on "thinking" it means it can't crack it, try joining our discord server and ask in #coded-messages

**Comment by Jayy001** [comment]
https://discord.gg/aKzxn59W

**Comment by SkeletalDemise** [comment]
As @Jayy001 said Ciphey doesn't support Python 3.9 on Windows. Also you seemed to be running it in Python IDLE based on this: ```Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.```
Run `exit()` to get out of it and make sure `python --version` works.
Ciphey getting stuck on `Thinking...` usually means Ciphey can't decode/decrypt your text. Join the Discord server and post your text in the `#coded-messages` channel for help decoding/decrypting it. 😄
