### ISSUE TITLE
Cannot decode www.google.com in base64 but http://www.google.com works

### ISSUE THREAD

**Issue by thezakman** [Ciphey/Ciphey#692]
**⚠️IMPORTANT⚠️ if you do not fill this out, we will automatically delete your issue. We will not help anyone that cannot fill out this template.**

- [ ] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)

**Describe the bug**

**Plaintext**
**⚠️IMPORTANT⚠️ The below code is non-negotiable for "Ciphey didn't decrypt...." problems. If you do not tell us your plaintext, we will not help you.** 

```

 ✘  thezakman@SRV-WEB1 ~  echo "http://www.google.com" | base64
aHR0cDovL3d3dy5nb29nbGUuY29tCg==

 thezakman@SRV-WEB1  ~  ciphey -t "aHR0cDovL3d3dy5nb29nbGUuY29tCg=="
Possible plaintext: 'http://www.google.com\n' (y/N): y
╭───────────────────────────────────────────────────╮
│ The plaintext is a Uniform Resource Locator (URL) │
│ Formats used:                                     │
│    base64                                         │
│    utf8Plaintext: "http://www.google.com          │
│ "                                                 │
╰───────────────────────────────────────────────────╯
 thezakman@SRV-WEB1  ~  ciphey -t "aHR0cDovL3d3dy5nb29nbGUuY29tCg=="

  thezakman@SRV-WEB1  ~  echo "www.google.com" | base64
d3d3Lmdvb2dsZS5jb20K

 pedro@SRV-WEB-CRAWLER01  ~  ciphey -t "d3d3Lmdvb2dsZS5jb20K"
Possible plaintext: 'TyT DaLiOk\rmLc)' (y/N): n
Possible plaintext: ')cLm\rkOiLaD TyT' (y/N): n
🌒  Thinking... (crashed | forever waiting)

```
**Version**
**⚠️IMPORTANT⚠️ We need this information because different environments will induce different bugs in Ciphey**
 - OS/Distro: [e.g. Windows, Debian 11.0, Arch, OS X El Capitan]
 - Python version: [python3 --version]
 - Ciphey versions: [python3 -m pip show ciphey cipheycore cipheydists]
 - Did you use Docker?

**Verbose Output**
**⚠️IMPORTANT⚠️ Verbose output will tell us why it's not working the way we expected it to be.**
Run Ciphey with `ciphey -vvv` and paste the results into [Pastebin.com](https://pastebin.com) or a [GitHub Gist](https://gist.github.com/)

**To Reproduce**
1. What input did you use?
2. What flags / arguments did you use?

**Expected behavior**
It should decode it and not crash the app like it's doing right now.

**Any other information?**

**Comment by SkeletalDemise** [comment]
This isn't a bug with Ciphey. Update your [pyWhat](https://github.com/bee-san/pyWhat) version with `pip install pywhat -U` as Ciphey uses pyWhat for identifying URLs, API keys, phone numbers, etc.
