### ISSUE TITLE
Ciphey can't decrypt Caesar(7)+Base64+Reverse

### ISSUE THREAD

**Issue by aydenbottos** [Ciphey/Ciphey#703]
**⚠️IMPORTANT⚠️ if you do not fill this out, we will automatically delete your issue. We will not help anyone that cannot fill out this template.**

- [Yes] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)

**Describe the bug**
Ciphey fails to decrypt a text encoded in this order: Caesar(7)+Base64+Reverse.

**Plaintext**
**⚠️IMPORTANT⚠️ The below code is non-negotiable for "Ciphey didn't decrypt...." problems. If you do not tell us your plaintext, we will not help you.** 

```
Nords are so serious about beards
```
**Version**
**⚠️IMPORTANT⚠️ We need this information because different environments will induce different bugs in Ciphey**
 - OS/Distro: [Arch Linux]
 - Python version: [3.9.7]
 - Ciphey versions: [5.14.0]
 - Did you use Docker? No

**Verbose Output**
**⚠️IMPORTANT⚠️ Verbose output will tell us why it's not working the way we expected it to be.**
https://gist.github.com/aydenbottos/214914aeeda6e4ddc8f55890e64222f5

**To Reproduce**
1. What input did you use? 6tWeoxWagEmY2lGagonY2BXespHI2pHIslHago3a5ZXV
2. What flags / arguments did you use? -t

**Expected behavior**
I expected Ciphey to decode the input and return it in plaintext.

**Any other information?**
The computer I am running from has an i7-11800H with 8 cores, RTX 3060 and 16GB of RAM so definitely not hardware.
Also tried on Google Colab.

**Comment by SkeletalDemise** [comment]
This is the same issue as #606 so I'll close this to merge it into one issue. Ciphey has a known bug where it can't decode and decrypt a plaintext that's been encrypted with the Caesar cipher and then encoded with Base64.
