### ISSUE TITLE
attempted relative import with no known parent package

### ISSUE THREAD

**Issue by jsjbcyber** [Ciphey/Ciphey#708]
ImportError: attempted relative import with no known parent package；
try to run "python ciphey.py" ...... I don't know how to solve this, did anyone have this problem?

**Comment by SkeletalDemise** [comment]
Closing this issue because you didn't fill out the issue template. Follow the installation instructions to install Ciphey, you can't run `ciphey.py` directly: https://github.com/Ciphey/Ciphey/wiki/Installation
