### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by jsjbcyber** [Ciphey/Ciphey#709]
**⚠️IMPORTANT⚠️ if you do not fill this out, we will automatically delete your issue. We will not help anyone that cannot fill out this template.**

- [x] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)
yes
**Describe the bug**
i tried to run "python ciphey.py" but ... "ImportError: attempted relative import with no known parent package"
![image](https://user-images.githubusercontent.com/75512150/139970944-bc0ded0c-6984-42f1-bed6-2017147b3510.png)

**Plaintext**
**⚠️IMPORTANT⚠️ The below code is non-negotiable for "Ciphey didn't decrypt...." problems. If you do not tell us your plaintext, we will not help you.** 

```
python ciphey.py
```
**Version**
**⚠️IMPORTANT⚠️ We need this information because different environments will induce different bugs in Ciphey**
 - OS/Distro: win10
 - Python version: python-3.8.6
 - Ciphey versions: ciphey-5.14.0
 - Did you use Docker? No

**Verbose Output**
**⚠️IMPORTANT⚠️ Verbose output will tell us why it's not working the way we expected it to be.**
Run Ciphey with `ciphey -vvv` and paste the results into [Pastebin.com](https://pastebin.com) or a [GitHub Gist](https://gist.github.com/)

**To Reproduce**
1. What input did you use? cmd
2. What flags / arguments did you use? just python ciphey.py or python ciphey.py -t

**Expected behavior**
How to fix this import Error

**Any other information?**
No

**Comment by SkeletalDemise** [comment]
As I said in your last issue you can't run `ciphey.py` directly. You have to install it via pip or Docker on Windows. Please read the installation instructions for how to install Ciphey: https://github.com/Ciphey/Ciphey/wiki/Installation

**Comment by jsjbcyber** [comment]
it works! thx!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ciphey/Ciphey"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月3日(星期三) 上午9:24
***@***.***&gt;;
抄送:&nbsp;"Mr. ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ciphey/Ciphey] ImportError: attempted relative import with no known parent package (Issue #709)





 
As I said in your last issue you can't run ciphey.py directly. You have to install it via pip or Docker on Windows. Please read the installation instructions for how to install Ciphey: https://github.com/Ciphey/Ciphey/wiki/Installation
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
