### ISSUE TITLE
Pass decrypted/encrypted text sample to speed up decryption process (when a user does not know which encryption algorithm was used)

### ISSUE THREAD

**Issue by AIGeneratedUsername** [Ciphey/Ciphey#711]
I do not know much about cryptography, so sorry if my question and future request looks stupid.

### Problem:
I have a huge encrypted text. I know nothing about how it is encrypted.

At the same time, a I have a few decrypted paragraphs of that text (I have a decrypted paragraph and I have an encrypted the same paragraph).  

### Question and (maybe) future request

Can I pass an encrypted/decrypted small sample to speed up a whole process?

If this can speed up a whole process, maybe you can consider this as a new feature for the package?

**Comment by SkeletalDemise** [comment]
You can use the regex checker if you know part of the plaintext. Example: `ciphey -t "Example4928" -C regex -p regex.regex=Example`
If Ciphey gets stuck on `Thinking...` for longer than a minute that usually means Ciphey can't decode/decrypt your code.
