### ISSUE TITLE
ciphey is not recognized as a internal command 

### ISSUE THREAD

**Issue by rage0920** [Ciphey/Ciphey#712]
### Problem:
ive been trying to run ciphey on windows server 2016 (aws instance) when i try to run it , it throws me an error saying  

'ciphey' is not recognized as an internal or external command,
operable program or batch file.

how do i fix this..?? someone please help!

**Comment by SkeletalDemise** [comment]
Closing because you didn't fill out the issue template. Also you should read the installation guide: https://github.com/Ciphey/Ciphey/wiki/Installation
If you're using Python 3.9 or Python 3.10 it won't work.
