### ISSUE TITLE
aes is support？

### ISSUE THREAD

**Issue by xuejiandong** [Ciphey/Ciphey#714]
### Problem:
_What exactly do you think is missing? How does it impact you? Are there any hacks that people use instead?_

### Solution:
_How could this problem be solved? What could be added? How could it be integrated into the current system?_

**Comment by SkeletalDemise** [comment]
No, cracking AES isn't supported. The currently supported encodings/ciphers are listed on this page:
https://github.com/Ciphey/Ciphey/wiki/Supported-Ciphers
