### ISSUE TITLE
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

### ISSUE THREAD

**Issue by Lantern-r** [Ciphey/Ciphey#715]
**⚠️IMPORTANT⚠️ if you do not fill this out, we will automatically delete your issue. We will not help anyone that cannot fill out this template.**

- [ x ] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)

**Describe the bug**
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

**Plaintext**
**⚠️IMPORTANT⚠️ The below code is non-negotiable for "Ciphey didn't decrypt...." problems. If you do not tell us your plaintext, we will not help you.** 

```
ciphey -t "ZmxhZ3tjaXBoZXlfaXNfc29fY29vbH0="
```
**Version**
**⚠️IMPORTANT⚠️ We need this information because different environments will induce different bugs in Ciphey**
 - OS/Distro: WSL Ubuntu18.04
 - Python version: python3.6
 - Ciphey versions: ciphey:4.2.1 cipheycore:0.1.5 cipheydists:0.2.2
 - Did you use Docker? No

**Verbose Output**
` ciphey -t "ZmxhZ3tjaXBoZXlfaXNfc29fY29vbH0="` can't work.
![image](https://user-images.githubusercontent.com/64698811/143182540-f9d89c61-5735-4563-a178-55e8f7c510e3.png)
But `ciphey -t "aGVsbG8gbXkgbmFtZSBpcyBiZWU="` can work.
![image](https://user-images.githubusercontent.com/64698811/143182752-b715d2c9-b1d6-40fa-a844-ada19d7a7388.png)

**Comment by SkeletalDemise** [comment]
Ciphey doesn't work with Python 3.6. The version you've installed is extremely old. You'll need to use Python 3.7+ as stated in the [installation instructions](https://github.com/Ciphey/Ciphey/wiki/Installation).
