### ISSUE TITLE
[Linux] Installation with brew failed asking to build from source.

### ISSUE THREAD

**Issue by darkRaspberry** [Ciphey/Ciphey#717]
- [x] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)

**Describe the bug**
Installation with Brew failed asking to build from source.

**Version**
**⚠️IMPORTANT⚠️ We need this information because different environments will induce different bugs in Ciphey**
 - OS/Distro: Ubuntu 21.10
 - Python version: Python 3.9.7 (N/A)
 - Ciphey versions: [python3 -m pip show ciphey cipheycore cipheydists]
 - Did you use Docker? NO

**Verbose Output**
```bash
 !  ~  ➜ brew install ciphey
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 2 formulae.

Error: ciphey: no bottle available!
You can try to install from source with:
  brew install --build-from-source ciphey
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

**To Reproduce**
Try to install. Run 
`brew install ciphey`

**Expected behavior**
Successfully install ciphey on my linux using Homebrew(linuxbrew)

**Any other information?**
Its asking for building from source. Which I don't prefer. If I want to build the app. I would download the repository directly from github and build it.

**Comment by SkeletalDemise** [comment]
Hi, this looks like an issue with homebrew and not Ciphey as Ciphey does work with Python 3.9 on Linux.
Looking at this similar [issue](https://stackoverflow.com/questions/66621710/homebrew-no-bottle-available) it could be a problem with the homebrew mirror you've selected or your directories. Try running `brew doctor` and `brew upgrade` and see if you get any errors.

**Comment by darkRaspberry** [comment]
Look like I didn't explained my issue.

Brew install require bottle to install. without that, it will not install.
If you look on the formula page - https://formulae.brew.sh/formula/ciphey or simply the file https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/ciphey.rb
![Screenshot from 2021-12-22 12-10-48](https://user-images.githubusercontent.com/56693429/147047451-0f14ff63-4cee-4012-be57-123d914bc6e8.png)

There must be a bottle `x86_64_linux` to make it install


If you look at any other brew formula which is installable on linux. It contain that bottle. for example - https://formulae.brew.sh/formula/python@3.9
![Screenshot from 2021-12-22 12-10-07](https://user-images.githubusercontent.com/56693429/147047360-12d1ca4a-f969-4eff-ad73-5b335ed763bb.png)
See there is linux-64 bit support for linux.

Currently ciphey doesn't really support installation from linux.

**Comment by SkeletalDemise** [comment]
Ok that makes sense. In that case you'll have to make an issue with homebrew as we don't manage the homebrew formula.
Pinging @harens who made the MacPorts port and helped with the homebrew formula.

**Comment by harens** [comment]
Thanks @SkeletalDemise for pinging me.

I have a feeling that this is to do with https://github.com/Homebrew/homebrew-core/pull/80479#issuecomment-873445544:

> if you rebase this the Linux CI should be green, we do not build Linux bottles for new formulae (yet) here. I fixed the CI for that case.

CC @iMichka who might be able to help :)

It shouldn't be too hard for the Homebrew maintainers to build a bottle via [dispatch-build-bottle](https://github.com/Homebrew/homebrew-core/actions/workflows/dispatch-build-bottle.yml).

**Comment by iMichka** [comment]
I tried to run a build but it failed because it requires c++20. I opened a pull request to try to fix the linux build: https://github.com/Homebrew/homebrew-core/pull/91957

**Comment by iMichka** [comment]
The build on Linux was fixed with https://github.com/Homebrew/homebrew-core/pull/91957, you can now `brew update` and install `ciphey`.

**Comment by darkRaspberry** [comment]
Yup installation is successful, i can `ciphey --help` to see the help. But when i input a random base64 string to decode, it freezes now after thinking for some time. Look like some python issue. I have investigate more why this is happening.

This current issue is solved moving ahead to close it.

**Comment by darkRaspberry** [comment]
Look like it is a known issue.
https://github.com/Ciphey/Ciphey/issues/718 This. Ciphey can't decode random text in base64
