### ISSUE TITLE
ciphey -t 'YXNkZmdoamtsMTIzNDU2Nzg5MA=='  

### ISSUE THREAD

**Issue by wpf973** [Ciphey/Ciphey#718]
ciphey -t 'YXNkZmdoamtsMTIzNDU2Nzg5MA=='  

└─$ ciphey -t 'YXNkZmdoamtsMTIzNDU2Nzg5MA=='                                                                              130 ⨯
🌘  Thinking...

![image](https://user-images.githubusercontent.com/22835238/146939823-a86b00ba-2c02-414e-99d9-5afe0d5161a5.png)

**Comment by Jayy001** [comment]
Hi, this normally means that Ciphey cannot crack the text given. 

Feel free to join the discord server and pop a message in #coded-messages. Hopefully somebody will be able to help you 🙂

**Comment by wpf973** [comment]
![image](https://user-images.githubusercontent.com/22835238/146963784-4b0a0701-c5bd-481f-8e71-d923be9de585.png)

**Comment by SkeletalDemise** [comment]
Hello, this isn't a bug. Your Base64 `YXNkZmdoamtsMTIzNDU2Nzg5MA==` decodes to `asdfghjkl1234567890` which isn't proper English or anything that Ciphey's checkers would catch. This is how Ciphey checks if something is successfully decoded/decrypted or not: https://github.com/Ciphey/Ciphey/wiki/Checkers,-explained
If it's not English, JSON, or anything in [pyWhat](https://github.com/bee-san/pyWhat) (URLs, API keys, email addresses, phone numbers, etc.) then Ciphey won't catch it.

If you want to test Ciphey try running this: `ciphey -t "VGhpcyBpcyBhbiBleGFtcGxlIG9mIEJhc2U2NCBlbmNvZGVkIHRleHQu"`
