### ISSUE TITLE
Add Enigma cracker and encoder/decoders

### ISSUE THREAD

**Issue by eabase** [Ciphey/Ciphey#724]
One way to crack enigma is by using MCMC, as shown here:

* https://towardsdatascience.com/breaking-the-enigma-code-in-python-with-mcmc-marvel-themed-9ceb358dd8ae
* https://github.com/JackWillz/Projects/blob/master/MCMC%20-%20Enigma%20Thanos/BreakEnigma.ipynb
* https://gist.github.com/JackWillz/d99deb8323540216bcaa932150ad71e0#file-mcmc-py

Other links I have added to #63

**Comment by moosterhof** [comment]
From what I can see, it's a mono-alphabetic substitution that's solved in the article. Apart from mentioning the words `turing` and `enigma` a lot, it has nothing to do with the actual enigma algorithm.

**Comment by SkeletalDemise** [comment]
As mentioned, that's not an actual enigma cipher cracker. Trying to crack the enigma cipher with no key is pretty complex and would be too slow in Python. Closing this due to not being feasible.
More information: http://practicalcryptography.com/cryptanalysis/breaking-machine-ciphers/cryptanalysis-enigma/

**Comment by eabase** [comment]
@moosterhof 

> From what I can see, it's a mono-alphabetic substitution that's solved in the article. Apart from mentioning the words `turing` and `enigma` a lot, it has nothing to do with the actual enigma algorithm.

Michael, I don't know what you have been looking at but I seem that your evaluation of the provided links are completely wrong. 
Maybe actually visit the 20+ links or so to the solutions? 

@SkeletalDemise 
> Trying to crack the enigma cipher with no key is pretty complex and would be too slow in Python. Closing this due to not being feasible.

I think you're also wrong there. It's obviously not that complex, as it has been repeatedly done in most basic courses on cryptography. There are ~20 links to different implementations. Take a pick. But don't tell me that Python doesn't perform better today than C-code did 10 years ago. You'll most likely break the enigma in less than a minute on modern laptop.

**Comment by SkeletalDemise** [comment]
https://towardsdatascience.com/breaking-the-enigma-code-in-python-with-mcmc-marvel-themed-9ceb358dd8ae
This article has nothing to do with the enigma cipher despite the title. It's clickbait. The ciphertext cracked in the article is a monoalphabetic substitution cipher with a custom alphabet. Which is way easier to crack than enigma.

You can quickly disprove its enigma by just looking at the ciphertext and the plaintext:
```
huvw !kzcq7nv3 qv3!hqv ,evwrhq
My children, the time has come
```
You can see that the same letters/numbers always correspond with the same letter. The enigma cipher is the opposite, it's polyalphabetic.

As for your other links, they're implementations of enigma cipher encoders/decoders in various programming languages.
Ciphertext-only attacks on enigma are slow and aren't taught in basic cryptography courses.

Even the C code in the article I linked is slow and didn't work on the ciphertexts that I tried.
