### ISSUE TITLE
PIP install error

### ISSUE THREAD

**Issue by Knocks83** [Ciphey/Ciphey#728]
**⚠️IMPORTANT⚠️ if you do not fill this out, we will automatically delete your issue. We will not help anyone that cannot fill out this template.**

- [x] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)

**Describe the bug**
I'm trying to install Ciphey on Windows, but pip gives me an error. Before switching to Docker, I thought about reporting it and checking if you could help me.

**Version**
**⚠️IMPORTANT⚠️ We need this information because different environments will induce different bugs in Ciphey**
 - OS/Distro: Windows 11
 - Python version: Python 3.10.2
 - Ciphey versions: Not installed
 - Did you use Docker? Nope
 - Sys.version: 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]

**Verbose Output**
**⚠️IMPORTANT⚠️ Verbose output will tell us why it's not working the way we expected it to be.**
Run Ciphey with `ciphey -vvv` and paste the results into [Pastebin.com](https://pastebin.com) or a [GitHub Gist](https://gist.github.com/)

https://gist.github.com/Knocks83/950b39c9d5bd7013c409b97b56ccc3e4

**To Reproduce**
1. pip install ciphey --upgrade

**Comment by amadejpapez** [comment]
Ciphey doesn't work on Windows with Python 3.9+, use Python 3.7 or Python 3.8. Other platforms are fine with Python 3.9, Python 3.10 doesn't work.

[Installation Guide](https://github.com/Ciphey/Ciphey/wiki/Installation)

**Comment by Knocks83** [comment]
Oh sorry, I didn't notice it. Thanks for the help!
