### ISSUE TITLE
Update Documentation for Wordlist

### ISSUE THREAD

**Issue by gleporeNARA** [Ciphey/Ciphey#742]
Is the wordlist used to provide cribs for decoding certain ciphers, or to provide keys for decoding vigenere ciphers? I don't see any discussion on the format of the wordlist, or exactly how it is used. I assume it is a text file with one keyword per line, but I'm not sure.

**Comment by SkeletalDemise** [comment]
If you mean the wordlist provided by the config file then that isn't used.
Ciphey uses various wordlists for our checkers: https://github.com/Ciphey/Ciphey/wiki/Checkers,-explained
