### ISSUE TITLE
`xortool_ciphey` seems to be not on GitHub. Where is it?

### ISSUE THREAD

**Issue by KOLANICH** [Ciphey/Ciphey#748]
### Idea
See source code repo of `xortool_ciphey`.

**Comment by SkeletalDemise** [comment]
We use a fork of xortool for the XOR cracker.
Here's the repo: https://github.com/bee-san/xortool

**Comment by KOLANICH** [comment]
Thanks for the info. Is it feasible to upstream the needed changes or to wrap the original `xortool`?
