### ISSUE TITLE
install failed 

### ISSUE THREAD

**Issue by a-gamer** [Ciphey/Ciphey#759]
every time i try to install get this error with v 3.7
3.9

on termux  
phone poco x3
android 11

(setup.py) ... done                Collecting pyasn1-modules==0.2.8                          Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
     ━━━━━━━━━━━━━━━ 155.3/155.3 kB 1.4 MB/s eta 0:00:00
Collecting certifi==2020.4.5.1
  Downloading certifi-2020.4.5.1-py2.py3-none-any.whl (157 kB)                                                       ━━━━━━━━━━━━━━━ 157.0/157.0 kB 1.2 MB/s eta 0:00:00Collecting tensorboard-plugin-wit==1.6.0.post3
  Downloading tensorboard_plugin_wit-1.6.0.post3-py3-none-any.whl (777 kB)                                           ━━━━━━━━━━━━━━━ 777.2/777.2 kB 1.5 MB/s eta 0:00:00Collecting tensorflow-estimator==2.2.0
  Downloading tensorflow_estimator-2.2.0-py2.py3-none-any.whl (454 kB)                                               ━━━━━━━━━━━━━━━ 454.6/454.6 kB 2.4 MB/s eta 0:00:00Collecting google-auth-oauthlib==0.4.1
  Downloading google_auth_oauthlib-0.4.1-py2.py3-none-any.whl (18 kB)                                           Collecting numpy==1.18.4                                  Downloading numpy-1.18.4.zip (5.4 MB)
     ━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 2.9 MB/s eta 0:00:00  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting oauthlib==3.1.0
  Downloading oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)                                                           ━━━━━━━━━━━━━━ 147.4/147.4 kB 10.6 MB/s eta 0:00:00
Collecting scipy==1.4.1
  Using cached scipy-1.4.1.tar.gz (24.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error           error: subprocess-exited-with-error                   
  × Preparing metadata (pyproject.toml) did not run successfully.                                                 │ exit code: 1                                          ╰─> [103 lines of output]                                   <string>:418: UserWarning: Unrecognized setuptools command ('dist_info --output-dir /data/data/com.termux/files/usr/tmp/pip-modern-metadata-490byrkz --keep-egg-info'), proceeding with generating Cython sources and expanding templates                                               Running from scipy source directory.                    lapack_opt_info:                                        lapack_mkl_info:
      customize UnixCCompiler                                   libraries mkl_rt not found in ['/data/data/com.termux/files/usr/lib']                                           NOT AVAILABLE
                                                              openblas_lapack_info:
      customize UnixCCompiler                                 customize UnixCCompiler
        libraries openblas not found in ['/data/data/com.termux/files/usr/lib']                                         NOT AVAILABLE                                   
      openblas_clapack_info:                                  customize UnixCCompiler
      customize UnixCCompiler                                   libraries openblas,lapack not found in ['/data/data/com.termux/files/usr/lib']                                  NOT AVAILABLE
                                                              flame_info:
      customize UnixCCompiler                                   libraries flame not found in ['/data/data/com.termux/files/usr/lib']                                            NOT AVAILABLE                                   
      atlas_3_10_threads_info:
      Setting PTATLAS=ATLAS                                   customize UnixCCompiler
        libraries lapack_atlas not found in /data/data/com.termux/files/usr/lib                                       customize UnixCCompiler
        libraries tatlas,tatlas not found in /data/data/com.termux/files/usr/lib                                      <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
        NOT AVAILABLE
                                                              atlas_3_10_info:                                        customize UnixCCompiler                                   libraries lapack_atlas not found in /data/data/com.termux/files/usr/lib
      customize UnixCCompiler                                   libraries satlas,satlas not found in /data/data/com.termux/files/usr/lib                                      <class 'numpy.distutils.system_info.atlas_3_10_info'>
        NOT AVAILABLE                                   
      atlas_threads_info:
      Setting PTATLAS=ATLAS
      customize UnixCCompiler
        libraries lapack_atlas not found in /data/data/com.termux/files/usr/lib                                       customize UnixCCompiler
        libraries ptf77blas,ptcblas,atlas not found in /data/data/com.termux/files/usr/lib
      <class 'numpy.distutils.system_info.atlas_threads_info'>
        NOT AVAILABLE                                                                                                 atlas_info:
      customize UnixCCompiler                                   libraries lapack_atlas not found in /data/data/com.termux/files/usr/lib
      customize UnixCCompiler
        libraries f77blas,cblas,atlas not found in /data/data/com.termux/files/usr/lib                                <class 'numpy.distutils.system_info.atlas_info'>          NOT AVAILABLE

      accelerate_info:                                          NOT AVAILABLE                                   
      lapack_info:                                            customize UnixCCompiler
        libraries lapack not found in ['/data/data/com.termux/files/usr/lib']                                           NOT AVAILABLE
                                                              /data/data/com.termux/files/usr/tmp/pip-build-env-d2zpnyeu/overlay/lib/python3.9/site-packages/numpy/distutils/system_info.py:1712: UserWarning:                            Lapack (http://www.netlib.org/lapack/) libraries not found.
          Directories to search for the libraries can be specified in the                                                 numpy/distutils/site.cfg file (section [lapack]) or by setting
          the LAPACK environment variable.
        if getattr(self, '_calc_info_{}'.format(lapack))():                                                           lapack_src_info:                                          NOT AVAILABLE

      /data/data/com.termux/files/usr/tmp/pip-build-env-d2zpnyeu/overlay/lib/python3.9/site-packages/numpy/distutils/system_info.py:1712: UserWarning:                            Lapack (http://www.netlib.org/lapack/) sources not found.
          Directories to search for the sources can be specified in the                                                   numpy/distutils/site.cfg file (section [lapack_src]) or by setting
          the LAPACK_SRC environment variable.
        if getattr(self, '_calc_info_{}'.format(lapack))():
        NOT AVAILABLE
                                                              Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()                                                File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main                                        json_out['return_val'] = hook(**hook_input['kwargs'])                                                         File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)                                                              File "/data/data/com.termux/files/usr/tmp/pip-build-env-d2zpnyeu/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-d2zpnyeu/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 484, in run_setup                    super(_BuildMetaLegacyBackend,
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-d2zpnyeu/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())                                  File "<string>", line 540, in <module>
        File "<string>", line 536, in setup_package             File "/data/data/com.termux/files/usr/tmp/pip-build-env-d2zpnyeu/overlay/lib/python3.9/site-packages/numpy/distutils/core.py", line 137, in setup
          config = configuration()                              File "<string>", line 435, in configuration
      numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.                                      [end of output]                                                                                             note: This error originates from a subprocess, and is likely not a problem with pip.                          error: metadata-generation-failed                                                                               × Encountered error while generating package metadata.  ╰─> See above for output.                               
note: This is an issue with the package mentioned above, not pip.                                               hint: See above for details.

**Comment by a-gamer** [comment]
i have  try install  it with this command 

apt-get install python-scipy
and working  fine  when  use 
pip install ciphey --force 
Using cached keyring-21.2.0-py3-none-any.whl (30 kB)  Collecting ciphey                                         Using cached Ciphey-3.0.6-py3-none-any.whl (6.1 MB)     Using cached Ciphey-3.0.5-py3-none-any.whl (43 kB)    Installing collected packages: ciphey                   Successfully installed ciphey-3.0.5



but when  try to call it .by type 
ciphey -t "data"
got that it's  not installed 


ciphey -t "fhnnnhhgffgfdffd"                   
     No command ciphey found, did you mean:                   Command cf-key in package cfengine                      Command gopher in package gopher                        Command chem in package groff                           Command ipset in package ipset                          Command cjpeg in package libjpeg-turbo-progs            Command vipe in package moreutils

**Comment by SkeletalDemise** [comment]
Hello. I'm closing this because Ciphey doesn't work on phones.
Also Python 3.9 isn't supported except for Linux.

**Comment by a-gamer** [comment]
I'm  using termux  it's  linux

**Comment by SkeletalDemise** [comment]
That doesn't matter, Ciphey doesn't have builds for mobile architectures. That's why you can't install it on mobile.
