### ISSUE TITLE
Quick question:What is the reason for Ciphey to not work with Windows Py3.9+?

### ISSUE THREAD

**Issue by RESDXChgfore9hing** [Ciphey/Ciphey#763]
### Idea
Can we attempt to fix it?
Is this a python problem or a c++ problem?

If its strictly c++ compilation problem we can try rust for those parts.
Since compiling numeric intensive in rust has similar performance,

### Pros
If we could solve it then we can make it works in windows ,which make the notice>
Ciphey can only work in py3.7&3.8 in windows not needed.

### Cons
may need to take a look at rust py and make the cipheycore more complex.

**Comment by bee-san** [comment]
Hi!

We are actually rewriting Ciphey entirely in Rust over on https://github.com/bee-san/Ares

:)

**Comment by bee-san** [comment]
https://github.com/Ciphey/Ciphey/issues/764 :)

**Comment by RESDXChgfore9hing** [comment]
I see hahaha,nice well I will just close this issue and try out ares instead.
