### ISSUE TITLE
Bump version of absl-py to 0.12.0

### ISSUE THREAD

**Issue by RESDXChgfore9hing** [Ciphey/Ciphey#765]
**⚠️IMPORTANT⚠️ if you do not fill this out, we will automatically delete your issue. We will not help anyone that cannot fill out this template.**

- [ - ] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)

**Describe the bug**
install fail 

https://github.com/abseil/abseil-py/issues/208

**Version**
**⚠️IMPORTANT⚠️ We need this information because different environments will induce different bugs in Ciphey**
 - OS/Distro: [e.g. Windows
 - Python version: 3.11.1
 - Ciphey versions: -
 - Did you use Docker?No

**Verbose Output**
has a copy at https://github.com/abseil/abseil-py/issues/208

**Comment by bee-san** [comment]
We do not use ABSL per https://github.com/Ciphey/Ciphey/blob/master/pyproject.toml
