### ISSUE TITLE
Cannot install on Windows

### ISSUE THREAD

**Issue by macsmol** [Ciphey/Ciphey#809]
**⚠️IMPORTANT⚠️ if you do not fill this out, we will automatically delete your issue. We will not help anyone that cannot fill out this template.**

- [x] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)
yes

**Describe the bug**
I run install command. It fails with some stack trace. I dont see ciphey added to the PATH. See the attached
[command.txt](https://github.com/user-attachments/files/17530704/command.txt)
to see full log of commands run (includes python version that Im using

**Plaintext**
**⚠️IMPORTANT⚠️ The below code is non-negotiable for "Ciphey didn't decrypt...." problems. If you do not tell us your plaintext, we will not help you.** 

```
Include your plaintext here, replacing this 
```
**Version**
**⚠️IMPORTANT⚠️ We need this information because different environments will induce different bugs in Ciphey**
 - OS/Distro: Windows 10 pro (version 22H2; OS build: 19045.5011)
 - Python version: Python 3.13.0
 - Ciphey versions: -
 - Did you use Docker? no

**Verbose Output**
**⚠️IMPORTANT⚠️ Verbose output will tell us why it's not working the way we expected it to be.**
Run Ciphey with `ciphey -vvv` and paste the results into [Pastebin.com](https://pastebin.com) or a [GitHub Gist](https://gist.github.com/)
-

**To Reproduce**
1. What input did you use?
python -m pip install -U ciphey
2. What flags / arguments did you use?

**Expected behavior**
To be able to run ciphey from cmd window

**Any other information?**
Please consider adding normal Windows installer? I run other software written in Python just fine - it was distributed with normal installer.

**Comment by pluto23-33** [comment]
i got the same issues, my python version is 3.11
